### ISSUE TITLE
As a student I would like to edit my Ampersand script without having to upload a file first.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#1]
# Symptoms
If I create a new script without uploading a file, I can type in a script myself.
However, when I save it, the whole thing disappears.
(sob)

**Comment by stefjoosten** [comment]
Thx @hanjoosten for solving this...

**Comment by hanjoosten** [comment]
That's wierd. I cannot remember solving anything. However, this is caused by the same bug as issue #6. Whenever that is solved, this issue will be solved as well.
