### ISSUE TITLE
Prototype geeft 404 page not found error bij invoegen bepaalde interface

### ISSUE THREAD

**Issue by attaxia** [AmpersandTarski/RAP#109]
#### De situatie
Prototype geeft 404 page not found error bij invoegen bepaalde interface

#### Wat er gebeurde er en wat had je verwacht?
Er zijn geen compile errors, en prototype lijkt gegenereed te worden. Alles zou dus moeten werken

#### Stappen om dit te reproduceren
Compile het volgende script, en run prototype:
```
CONTEXT Loonbewerking IN ENGLISH
PURPOSE CONTEXT Loonbewerking
{+ TODO
+}

-- Buildup of order
CONCEPT Order "Een order"
PURPOSE CONCEPT Order 
{+TODO+}
CONCEPT Ordernummer "Uniek identificatienummer voor order"
PURPOSE CONCEPT Ordernummer 
{+TODO+}
CONCEPT Ordertype "PM-ordertype"
PURPOSE CONCEPT Ordertype 
{+TODO+}
CONCEPT Orderstatus "Orderstatus"
PURPOSE CONCEPT Orderstatus
{+TODO+}

RELATION orderType [Order*Ordertype] [UNI, TOT]
MEANING "Geeft aan van welk type een order is"

RELATION orderNummer [Order*Ordernummer] [UNI, TOT]
MEANING "Een unieke identifier voor een order"

RELATION heeftStatus [Order*Orderstatus] [UNI, TOT]

-- Concepts around items
CONCEPT Artikel "Een artikel"
PURPOSE CONCEPT Artikel
{+TODO+}
CONCEPT Artikelnaam "Naam van artikel"
PURPOSE CONCEPT Artikelnaam
{+TODO+}
CONCEPT Artikelnummer ""
PURPOSE CONCEPT Artikelnummer
{+TODO+}
CONCEPT Serienummer "Een artikel"
PURPOSE CONCEPT Serienummer
{+TODO+}

-- Concepts around uitbesteding
CONCEPT Leverancier "Een uitvoerder van reparatieopdrachten"
PURPOSE CONCEPT Leverancier
{+TODO+}

RELATION artikelNummer [Artikel*Artikelnummer] [UNI, TOT]
MEANING "Elk artikel heeft een artikelnummer"

RELATION serieNummer [Artikel*Serienummer] [UNI]
MEANING "Een artikel heeft maximaal één serienummer"

RELATION artikelNaam [Artikelnummer*Artikelnaam] [UNI,TOT]
MEANING "Bij een artikelnummer hoort een naam voor het artikel"


-- Making relations between related concepts
RELATION bevatArtikel [Order*Artikel] [TOT]
MEANING "Beschrijft welke artikelen onderdeel uitmaken van een order"

RELATION isUitbesteedAan [Order*Leverancier] [UNI]
MEANING "Een order kan uitbesteed worden aan een externe leverancier"


-- Initial populations for concepts where applicable
POPULATION Ordertype CONTAINS
[ "PM01"
, "PM02"
, "PM03"
, "PM04"    
]

POPULATION Orderstatus CONTAINS
[ "Nieuw"
, "UGR"
, "Afgesloten"
]

POPULATION Leverancier CONTAINS
[ "Fokker"
, "Saab"
]

POPULATION artikelNaam CONTAINS
[ ("1", "Vleugel")
, ("2", "Schietstoel")
]


-- The relations and the initial population



INTERFACE Orders : "_SESSION"                  cRud
BOX <TABS>
     [ Order : V[SESSION*Order]             CRud
       BOX <TABLE>
                [ "Ordernummer" : orderNummer         CRUd
                , "Ordertype" : orderType cRUd
                ]
     ]

INTERFACE Artikels : "_SESSION"                  cRud
ROWS [ Artikelen : V[SESSION*Artikel]             CRud
      COLS  [ "Artikelnummer" : artikelNummer         cRUd
            , "Serienummer" : serieNummer CRUd
            , "Artikelnaam" : artikelNummer;artikelNaam cRud
            ]
     ]


ENDCONTEXT
```

#### Context / Source van ampersand script
Het probleem wordt veroorzaakt door de "Artikels" interface. Waarom is mij onduidelijk. Als ik deze weglaat dan werkt alles wel.
-->

**Comment by hanjoosten** [comment]
Dit komt door een wijziging in ampersand in release 4.1.0. In de [releasenotes](https://github.com/AmpersandTarski/Ampersand/blob/master/ReleaseNotes.md) kan je daar meer over lezen. Het komt er op neer dat je het woordje `ROWS` moet vervangen door `FORM`.

Blijkbaar is de documentatie _ergens_ niet meer actueel. Kan jij aangeven waar je je voorbeeld vandaan hebt? Dan kunnen we wellicht die documentatie bijwerken.

**Comment by attaxia** [comment]
Jazeker, dat komt hier vandaan:
https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/services/layout-of-user-interfaces

Maar ook gebruik van de zoekfunctie geeft nog vele andere pagina's aan met het keyword ROWS. Een fatsoenlijke error tijdens compilen zou wel fijn zijn.

**Comment by attaxia** [comment]
Het vervangen van ROWS door FROM zorgt trouwens wél voor een compile error:
```
/var/www/data/scripts/aaa/Script_1609238713_00028563/ScriptVersion_1609250333_00993252/script.adl:104:1 error:
  unexpected upper case identifier FORM
  expecting symbol '<', keyword "BOX", keyword "ROWS", keyword "COLS", keyword "TABS", keyword "LINKTO", keyword "INTERFACE" or keyword "API"
ExitFailure 10
```

**Comment by hanjoosten** [comment]
Hmm. Da's niet zo mooi. Op een of andere manier is blijkbaar de Ampersand compiler niet in sync met de prototype generator in RAP. Daar moet @stefjoosten even naar kijken, vrees ik. 

In de tussentijd zou je het woordje `ROWS` kunnen vervangen door `BOX`. Dat zou als workaround wel moeten werken, denk ik.

**Comment by stefjoosten** [comment]
Thank you @attaxia for submitting this issue. Han's diagnosis above is quite right. Version 4 of Ampersand (the current one) has a new syntax for interface directives. This is what we have to do:
1. Fix all examples in the documentation to prevent situations like this. At the moment only the tutorial has been adapted.
2. Fix the Ampersand parser to obtain correct error messages. If you accidentally use obsolete syntax, you want better messages.

**Comment by stefjoosten** [comment]
> Maar ook gebruik van de zoekfunctie geeft nog vele andere pagina's aan met het keyword ROWS. Een fatsoenlijke error tijdens compilen zou wel fijn zijn.

De foutmelding zou moeten zijn:
```
/var/www/data/scripts/aaa/Script_1609238713_00028563/ScriptVersion_1609250333_00993252/script.adl:104:1 error:
  unexpected upper case identifier ROWS
  expecting symbol '<', keyword "BOX", keyword "LINKTO", keyword "INTERFACE" or keyword "API"
ExitFailure 10
```

**Comment by stefjoosten** [comment]
@attaxia Je krijgt nu een betere foutmelding te zien, en daarmee sluit ik dit issue en het oude jaar af. Beste wensen voor het nieuwe jaar!

<img width="1490" alt="Schermafbeelding 2020-12-31 om 16 13 56" src="https://user-images.githubusercontent.com/275768/103415635-5394ed00-4b83-11eb-9a1e-da8e0714e5b5.png">
