### ISSUE TITLE
Every propertyRule must have a Property in relation to  xyz

### ISSUE THREAD

**Issue by gedelaar** [AmpersandTarski/RAP#128]
#### De situatie
bij het compileren van dit script krijg ik de melding zoals in het screenshot

#### Wat er gebeurde er en wat had je verwacht?
bestaand script dat in een eerdere versie niet deze meldingen opleverde

#### Stappen om dit te reproduceren
1. nieuw script
2. code inplakken
3. compileren
4.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/25302672/130599548-a153b321-a43c-4b59-a89f-a97aa6a47070.png)

#### Context / Source van ampersand script

CONTEXT Big IN ENGLISH
PURPOSE CONTEXT Big
{+ De wet op de Beroepen in de Individuele Gezondheidszorg+}

PATTERN Personen
-- The concepts
CONCEPT Wet "De wet-Big"
PURPOSE CONCEPT Wet 
{+Het kader waarin vastgelegd is welke beroepen in de gezondheidszorg werkzaam mogen zijn.+}
--
CONCEPT Bepaling "Toevoeging op de wet-BIG"
PURPOSE CONCEPT Bepaling
{+Veronderstelde verbeteringen op de Wet-Big+}
--
CONCEPT Persoon "Persoon die werkzaam wilt zijn binnen de zorg"
PURPOSE CONCEPT Persoon 
{+Vastleggen van de identiteit van de persoon+}
--
CONCEPT Handeling "Acties die uitgevoerd worden" 
PURPOSE CONCEPT Handeling 
{+Vastleggen van de mogelijke handelingen die uitgevoerd kunnen worden binnen de zorg+}
--
CONCEPT Specialisme "Specialiteit van een persoon zoals bedoeld in de wet" 
PURPOSE CONCEPT Specialisme 
{+Moet voorkomen in het specialismeregister+}
--
CONCEPT Beroep "Beroep van een persoon zoals bedoeld in de wet" 
PURPOSE CONCEPT Beroep 
{+Beroep dat uitgeoefend wordt+}
--
CONCEPT Registratie "De registratie van een persoon binnen het register" 
PURPOSE CONCEPT Registratie 
{+Vastlegging in het register geeft toegang tot uitoefenen taak binnen de gezondheidszorg+}

-- The relations and the initial population
RELATION beoefent  [Persoon*Beroep]
MEANING "Een Persoon oefent een Beroep uit"

POPULATION beoefent CONTAINS
[ ("Gerard", "Verpleger")
; ("Susan", "Arts")
; ("John", "Arts")
]
--
RELATION magUitvoeren[Beroep*Handeling]
MEANING "Binnen een Beroep mogen bepaalde Handelingen worden uitgevoerd"

POPULATION magUitvoeren[Beroep*Handeling] CONTAINS
[ ("Verpleger", "Pleister plakken")
; ("Verpleger", "Verbinden")
; ("Arts", "Injectie geven")
; ("Arts", "Amputeren")
; ("Tandarts", "Gaatjes vullen")
]
--
RELATION voertUit [Persoon*Handeling]
MEANING "Een Persoon voert Handelingen uit"

--
RELATION magUitvoeren[Specialisme*Handeling]
MEANING "Binnen een Specialisme mogen bepaalde Handelingen worden uitgevoerd"
--
RELATION beroepsbeoefenaar [Registratie*Persoon][TOT,UNI]
MEANING "Aan de registratie hangt een Persoon"
--
RELATION beroep [Registratie*Beroep] [TOT,UNI]
MEANING ""

-- The one rule in this model
--RULE ModulePersoon: voertUit |- beoefent;magUitvoeren[Beroep*Handeling]
RULE Beroepsrestrictie: voertUit; magUitvoeren[Beroep*Handeling]~ |- beroepsbeoefenaar~; beroep
MEANING "Een persoon mag handelingen uitvoeren wanneer hij een bepaald beroep beoefent"
MESSAGE "foutje."
VIOLATION (TXT "Persoon ", SRC I, TXT " voert de handeling uit ", TGT I, TXT " die niet tot zijn beroep behoren ", SRC I[Persoon];beoefent)
ENDPATTERN

INTERFACE Overview : "_SESSION"                  cRud
BOX <TABS>
     [ Persoon : V[SESSION*Persoon]             cRuD
       BOX <TABLE>
                [ "Persoon" : I[Persoon]         cRud
                , "Voert uit" : voertUit        CRUD
                , "Handeling" : beoefent         CRUD
                ]
     , Beroep : V[SESSION*Beroep]                cRuD
       BOX <TABLE>
                [ "Persoon" : I                   cRud
                , "Beroep" : beoefent~          CRUD
                ]
     ]

ENDCONTEXT
Ook horen we graag hoe je tot dit issue gekomen bent. 
-bij het uitproberen van RAP

Als dit een verzoek is voor een nieuwe feature, leg dan uit waarom je het wilt hebben en waartoe het dient.
-->

**Comment by stefjoosten** [comment]
# Analyse
Op `rap.cs.ou.nl` gaat het wel goed. Daar krijg ik dit te zien:
![afbeelding](https://user-images.githubusercontent.com/275768/130618376-52931a76-a325-48ec-9156-df493f68fbae.png)

De enige verklaring is dat de containers die op `rap.cs.ou.nl` draaien niet dezelfde containers zijn als die op jouw laptop draaien. Vanochtend dacht ik al aan deze oplossing want de gesignaleerde fout ziet er vergelijkbaar uit als de fout die ik kreeg enkele uren voor de uiteindelijke deployment naar `rap.cs.ou.nl` toe. Die heb ik toen opgelost, maar jouw installatie hebben we kennelijk net daarvoor gemaakt. Ik kijk even...

**Comment by stefjoosten** [comment]
Dit was een verkeerde container. Issue is opgelost.
