### ISSUE TITLE
Blank scherm na openen prototype

### ISSUE THREAD

**Issue by gedelaar** [AmpersandTarski/RAP#129]
#### De situatie
Na correcte compile en hierna aanmaken prototype, klik op de link van prototype.
Een nieuwe tab opent zich en deze is leeg.
![image](https://user-images.githubusercontent.com/25302672/130630451-b11ca33e-2711-4931-a98c-b1a4845e84e0.png)

#### Wat er gebeurde er en wat had je verwacht?
Ik had een gevuld scherm verwacht

#### Stappen om dit te reproduceren
1. script toevoegen
2. compile
3. prototype maken
4. prototype openen

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/25302672/130630789-3e9df1cc-684d-41e8-a3ad-9aa92dae5e10.png)

#### Context / Source van ampersand script
```Ampersand
CONTEXT Big IN ENGLISH
PURPOSE CONTEXT Big
{+ De wet op de Beroepen in de Individuele Gezondheidszorg+}

PATTERN Personen
-- The concepts
CONCEPT Wet "De wet-Big"
PURPOSE CONCEPT Wet 
{+Het kader waarin vastgelegd is welke beroepen in de gezondheidszorg werkzaam mogen zijn.+}
--
CONCEPT Bepaling "Toevoeging op de wet-BIG"
PURPOSE CONCEPT Bepaling
{+Veronderstelde verbeteringen op de Wet-Big+}
--
CONCEPT Persoon "Persoon die werkzaam wilt zijn binnen de zorg"
PURPOSE CONCEPT Persoon 
{+Vastleggen van de identiteit van de persoon+}
--
CONCEPT Handeling "Acties die uitgevoerd worden" 
PURPOSE CONCEPT Handeling 
{+Vastleggen van de mogelijke handelingen die uitgevoerd kunnen worden binnen de zorg+}
--
CONCEPT Specialisme "Specialiteit van een persoon zoals bedoeld in de wet" 
PURPOSE CONCEPT Specialisme 
{+Moet voorkomen in het specialismeregister+}
--
CONCEPT Beroep "Beroep van een persoon zoals bedoeld in de wet" 
PURPOSE CONCEPT Beroep 
{+Beroep dat uitgeoefend wordt+}
--
CONCEPT Registratie "De registratie van een persoon binnen het register" 
PURPOSE CONCEPT Registratie 
{+Vastlegging in het register geeft toegang tot uitoefenen taak binnen de gezondheidszorg+}

-- The relations and the initial population
RELATION beoefent  [Persoon*Beroep]
MEANING "Een Persoon oefent een Beroep uit"

POPULATION beoefent CONTAINS
[ ("Gerard", "Verpleger")
; ("Susan", "Arts")
; ("John", "Arts")
]
--
RELATION magUitvoeren[Beroep*Handeling]
MEANING "Binnen een Beroep mogen bepaalde Handelingen worden uitgevoerd"

POPULATION magUitvoeren[Beroep*Handeling] CONTAINS
[ ("Verpleger", "Pleister plakken")
; ("Verpleger", "Verbinden")
; ("Arts", "Injectie geven")
; ("Arts", "Amputeren")
; ("Tandarts", "Gaatjes vullen")
]
--
RELATION voertUit [Persoon*Handeling]
MEANING "Een Persoon voert Handelingen uit"

--
RELATION magUitvoeren[Specialisme*Handeling]
MEANING "Binnen een Specialisme mogen bepaalde Handelingen worden uitgevoerd"
--
RELATION beroepsbeoefenaar [Registratie*Persoon][TOT,UNI]
MEANING "Aan de registratie hangt een Persoon"
--
RELATION beroep [Registratie*Beroep] [TOT,UNI]
MEANING ""

-- The one rule in this model
--RULE ModulePersoon: voertUit |- beoefent;magUitvoeren[Beroep*Handeling]
RULE Beroepsrestrictie: voertUit; magUitvoeren[Beroep*Handeling]~ |- beroepsbeoefenaar~; beroep
MEANING "Een persoon mag handelingen uitvoeren wanneer hij een bepaald beroep beoefent"
MESSAGE "foutje."
VIOLATION (TXT "Persoon ", SRC I, TXT " voert de handeling uit ", TGT I, TXT " die niet tot zijn beroep behoren ", SRC I[Persoon];beoefent)
ENDPATTERN

INTERFACE Overview : "_SESSION"                  cRud
BOX <TABS>
     [ Persoon : V[SESSION*Persoon]             cRuD
       BOX <TABLE>
                [ "Persoon" : I[Persoon]         cRud
                , "Voert uit" : voertUit        CRUD
                , "Handeling" : beoefent         CRUD
                ]
     , Beroep : V[SESSION*Beroep]                cRuD
       BOX <TABLE>
                [ "Persoon" : I                   cRud
                , "Beroep" : beoefent~          CRUD
                ]
     ]

ENDCONTEXT
```

Waarneming: Dit script werkt correct op `rap.cs.ou.nl` en het werkt correct op Stef's MacBook, maar het heeft het hierboven beschreven gedrag op de laptop van Gerard. We hebben gecheckt dat de juiste containers draaien bij Gerard. Ook hebben we het systeem helemaal ververst (inclusief nieuwe volumes), maar het foute gedrag persisteert.

**Comment by Michiel-s** [comment]
@gedelaar wanneer het scherm blanco blijft duidt dit meestal op een javascript error. De frontend app kan dan niet laden waardoor je niets ziet. De browser zit als het ware vast.

Zou je de output van de browser console hier willen plaatsen? In Chrome krijg je die door de developer tools te openen `Ctrl-Shif-I`. Vervolgens het tabblad `Console` aanklikken.

Voor Firefox is er vergelijkbare functie, maar waarschijnlijk andere sneltoets/menu optie.

**Comment by gedelaar** [comment]
![image](https://user-images.githubusercontent.com/25302672/130752310-92710b6a-0b37-4616-93e7-9bb51cb51e1e.png)

in firefox en chrome vergelijkbare output op console 
eerste image is chrome
![image](https://user-images.githubusercontent.com/25302672/130752546-c6893fad-2f86-4635-8bb1-77e8dfa028b8.png)
tweede vanuit firefox.
met in firefox alle extenties uitgezet

**Comment by gedelaar** [comment]
![image](https://user-images.githubusercontent.com/25302672/130753176-f2e87616-3ce3-4d84-a879-1a01a15e492b.png)
screenshot van het script-scherm

**Comment by Michiel-s** [comment]
Vandaag heb ik contact gehad met @gedelaar en het probleem kunnen diagnosticeren.

## Analyse
De geconfigureerde database hostname `db` bleek niet te resolven door de student prototype container. De twee containers zaten niet in hetzelfde docker network. Maar hoe kan dit? Want in het RAP ExecEngine script waar de student prototype container wordt gecreëerd wordt deze expliciet aan het `rap_db` netwerk toegevoegd. Zie https://github.com/AmpersandTarski/RAP/blob/808eca1053d53b6c83c3df5ea9e165bc8e49bfce/RAP4/customizations/bootstrap/files/ExecEngineFunctions.php#L349

Daar zien we staan dat de container aan `rap_db` netwerk wordt toegevoegd. In het docker-compose.yml bestand wordt echter een `db` netwerk gedefinieerd, waar o.a. de database in zit. Zie https://github.com/AmpersandTarski/RAP/blob/808eca1053d53b6c83c3df5ea9e165bc8e49bfce/docker-compose.yml#L11-L14

Docker-compose prefixed echter volumes, networks, e.d met de naam van de map/folder waar de docker-compose.yml in staat. In dit geval meestal `rap`, want zo heet de repository hier, dus als die middels git checkout ophaald dan wordt deze automatisch in de map met naam `rap` gezet. Zo krijg je dus het netwerk `rap_db` bij `docker-compose up`.

Echter, @gedelaar had de map `rapinstall` genoemd. Dus de netwerknaam werd `rapinstall_db` terwijl de student prototype nog steeds hardcoded aan `rap_db` werd toegevoegd. Kortom, container en database konden elkaar niet bereiken.

## Oplossing
Ik stel voor om het netwerk `db` zoals gedefinieerd in `docker-compose.yml`, net als het `proxy` netwerk, external te maken. Dit zorgt ervoor dat deze niet meer geprefixed wordt, maar verondersteld wordt dat het docker netwerk reeds bestaat (net als proxy). Het makkelijks is om deze vervolgens `rap_db` te noemen, zodat er verder geen wijzigingen nodig zijn. Ik zal er ook een comment bij plaatsen waarom het netwerk external is en dat de naam moet zijn zoals deze is.

**Comment by stefjoosten** [comment]
Mooie analyse! Kan de oplossing ook zijn dat de prefix "rap" uit een variabele komt? En dan zo dat in het geval van Gerard er "rapinstall" had gestaan i.p.v. rap (zodat hij netjes aan rapinstall_db gekoppeld zou zijn geweest i.p.v. aan rap_db)?

**Comment by Michiel-s** [comment]
Ik ga nog een commit inschieten waarbij de docker-compose wordt aangepast.

**Comment by stefjoosten** [comment]
OK
