### ISSUE TITLE
Determine API calls used in RAP

### ISSUE THREAD

**Issue by JesseZwitserlood** [AmpersandTarski/RAP#136]
Before we can test the API calls in RAP we need to determine which ones are being used. By doing so we can make a list of taskt we still need to do and make a more concrete list of DoD's for the tests needed for the API call in question.

- [ ] Go through the RAP sollution and find all the API calls used by the program
- [ ] Document these API calls

**Comment by stefjoosten** [comment]
Test tools such as Gatling and JMeter have a recording function that lets you record a session, so you don't have to figure out all the API calls yourself....
