### ISSUE TITLE
Making machines ready for RAP

### ISSUE THREAD

**Issue by JesseZwitserlood** [AmpersandTarski/RAP#140]
The process (as described on the RAP home page) to make a machine ready to use RAP takes a while. So we need to make sure to take some time to let all the developers make their machines RAP ready

- [x] Figure out which developers are going to be working on this project
- [x] *Patrick & Bas* have installed everything
- [x] #139 needs to be done first

**Comment by CasperHooft** [comment]
poker 3

**Comment by stefjoosten** [comment]
Het deployen van RAP op je eigen machine is beschreven op https://ampersandtarski.gitbook.io/the-tools-we-use-for-ampersand/installation-of-rap/deploying-to-your-own-laptop.
