### ISSUE TITLE
Research, how does Kubernetes work?

### ISSUE THREAD

**Issue by JesseZwitserlood** [AmpersandTarski/RAP#145]
For this project we will be using Kubernetes, however, no one in the current team has experience with the software. This might cause problems if we don't take the proper time to familiarise ourselves with it.

- [x] Research how Kubernetes works 
----
- [x] Research how Kubernetes handles the creation of a database
- [x] Research how Kubernetes handles the interaction with the database

**Comment by stefjoosten** [comment]
Kubernetes houdt zich helemaal niet bezig met databases. Alleen met containers. Je moet dus kijken naar hoe de containerstructuur in elkaar zit. RAP gebruikt een MariaDB container, wat je kunt zien in het docker-compose.yml bestand van RAP.

Er bestaat ook Kompose. Dat is een conversion tool van Docker Compose naar container orchestrators (Kubernetes of OpenShift). Zie ook http://kompose.io/.
