### ISSUE TITLE
Convert Docker-compose to Kubernetes YAML file

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/RAP#148]
Kubernetes works with a YAML file to describe objects. The following [Ampersand documentation](https://ampersandtarski.github.io/docs/TheToolsWeUse/deploying-with-kubernetes) describes how to convert a Docker-compose file to a Kubernetes YAML file.

[Kompose](https://kompose.io/) can be used to convert an existing docker-compose file to a Kubernetes YAML file.
However, the YAML file generated by Kompose does not work directly and should be modified.

**Comment by Michiel-s** [comment]
I suggest to not use Kompose.

When you fully understand Docker compose and Kubernetes, you can use Kompose to scaffold kubernetes resources and check-improve them manually.

I don't believe that is the case in this team. So for learning purposes it's better to build the kubernetes resources from scratch.
