### ISSUE TITLE
Deploy RAP to Azure Container Instances

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/RAP#166]
**Purpose**
To deploy RAP to the Azure cloud we need to know if the Docker compose file can be used in its current form or if changes are required.

**Tasks**

- [ ] Deploy multi-container group to Azure Container Instances through Docker Compose:
https://learn.microsoft.com/en-us/azure/container-instances/tutorial-docker-compose

- [x] Create issues for problems

**Comment by basplijnaer** [comment]
labels cannot be used in container instances

**Comment by basplijnaer** [comment]
Getting the following error when trying to deploy to Azure Container Instances:
```
PS C:\Development\Ampersand\RAP> docker-compose up
[+] Running 0/1
 - Group rap  Error                                                                                                                                   37.2s 
containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. 
Status=<nil> Code="ServiceUnavailable" Message="The requested resource is not available in the location 'westeurope' at this moment. Please retry with a different resource request or in another location. Resource requested: '7' CPU '6.1' GB memory 'Linux' OS"
```

**Comment by hanjoosten** [comment]
@basplijnaer , I have no trouble running above command. However, to build this image you need more memory than docker grants by default. I guess you need to check your memory limit.

**Comment by basplijnaer** [comment]
We are now able to deploy to Azure Container Instances using: `docker compose up`. However, the containers keep restarting:

![Image](https://user-images.githubusercontent.com/13163139/196717680-935b847d-902c-41df-a0fb-778d0ce1b5b7.png)

**Comment by basplijnaer** [comment]
For `docker login azure` use: `docker login azure --tenant-id [tenant-id]`
