### ISSUE TITLE
Runtime RAP-switches made settable in localSettings.php

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#17]
In the RAP3 interface we have "Show/hide notification" with a horn shaped icon in the menubar.
For ordinary users in the production version of RAP3, I would like to remove that icon from the menubar entirely. Can we do that already? How?
I would like to set the runtime switches on the RAP3 interface for the students in localSettings.php.

**Comment by Michiel-s** [comment]
@stefjoosten, as discussed you can customize the navigation bar view for the RAP3 application, by putting the html file in the customizations/app/views folder.

The other option, A setting for the localsettings file can be introduced. I suggest to open a issue for this in de Ampersand repository. I’ll do this
