### ISSUE TITLE
Find an alternative for traefik

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/RAP#172]
**Purpose**
Traefik uses labels in the docker compose file. However, labels are not supported in Azure container instances.

**Tasks**
- [x] Find out what traefik is used for
- [ ] Implement Traefik with Azure or find an alternative

**Comment by Michiel-s** [comment]
Reverse proxy.
Traefik makes sure that incoming request are directed to the right service/container.

**Comment by sheriffBalunywa** [comment]
Ingress controller is found as an alternative
