### ISSUE TITLE
Test scenario: A user cannot register when user already exists

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/RAP#195]
1. User goes to the home page
2. User goes to the login page
3. User clicks register
4. User fills in userid (that already exists) and password
5. Should give an error message
6. User goes to MyScripts page
7. Page should give 401 not authorized

**Comment by Sharvin1** [comment]
C:\Users\sra32809\source\repos\RAP\Testing\Gatling\target\gatling\unsuccessfulregister-20221220100139058\index.html

**Comment by hanjoosten** [comment]
@Sharvin1 , de link die je hier hebt opgevoerd is een link naar jouw lokale c-schijf. Is er ook iets waar anderen dan jij kunnen zien dat dit testscenario het doet?
