### ISSUE TITLE
Epic: Automate deployment to Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#230]
As a consumer of RAP (or another Ampersand generated information system?), I want to be able to deploy to Azure with the least amount of effort. To do so, Azure command line interface (CLI) scripts are generated, where the flow of operations is defined.

When this epic is completed, a new deployment of an Ampersand application, scripts are available where only project specific parameters are required as input.

Tasks:
- [ ]

**Comment by stefjoosten** [comment]
Since Ordina-RAP and OUNL-RAP are both deployed and in production on AKS, I'm closing this issue.
