### ISSUE TITLE
Add ingress controller (nginx) to Kubernetes cluster

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#232]
**Purpose**
Get familiar with ingress, security (certification). Add an ingress controller (nginx) to Kubernetes cluster and configure to access cluster from the public domain.

**Subtasks**
- [x] Add deployment for ingress controller
- [x] Configure ingress controller to make phpmyadmin accessible

When finished we should be able to access phpmyadmin by something like:
https://phpmyadmin.ampersand-rap.azurewebsites.net

**Comment by Michiel-s** [comment]
For the non-RAP specific applications (like the database, phpmyadmin and ingress controller) my suggestion is to use Helm.

Documentation on that:
* MariaDB: https://bitnami.com/stack/mariadb/helm
* Phpmyadmin: https://bitnami.com/stack/phpmyadmin/helm
* Ingress controller: https://kubernetes.github.io/ingress-nginx/
* Cert-manager: https://cert-manager.io/docs/installation/helm/

For NGINX, use the version provided on kubernetes.github.io (not by NGINX itself)

**Comment by Michiel-s** [comment]
Issue marked done
