### ISSUE TITLE
Add enroll and dummy-student-prototype to Kubernetes cluster

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#233]
- [x] Add enroll and dummy-student-prototype to Kubernetes cluster
- [x] Check how dummy-student-prototype behaves (in Docker-compose it's killed directly after inializing)
- [x] Configure ingress controller to make enroll accessible

When finished we should be able to access phpmyadmin by something like:
https://enroll.ampersand-rap.azurewebsites.net/

**Comment by Michiel-s** [comment]
Issue marked done
