### ISSUE TITLE
Relation 'isa[Concept][*]' is not defined

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#25]
# Observation
When I generare an atlas (using the feature branch commit  378e3d78dc27e016b627c3309312d964d844bb84) , I get the following error:

![image](https://user-images.githubusercontent.com/1159672/31408536-38a0d268-ae09-11e7-86cc-7fece083c89b.png)

# Reproduction

  1.  Build Ampersand ( https://github.com/AmpersandTarski/Ampersand/tree/feature/MeatgrinderWithoutExpressions )
  2. Generate RAP3, using the normal switches: 

~~~.sh
ampersand.exe --meta-tables --add-semantic-metamodel --verbose RAP3.adl
~~~
  3. Login as a student
  4. press the *+* icon to create a new script.
  5. Add a script (I used DeliverySimple from the travis testset, but you can probably use any script)
  6. compile the script
  7. generate a formal specification document (this will enable the Atlas button)
  8. genarate an atlas.

**Comment by hanjoosten** [comment]
It might be that when an endorelation is used (like `isa[Concept*Concept]` ) there is something in RAP that tries to abbreviate it (as `isa[Concept]`). The php call doesn't seem to like that. 

I observed that the relation isa[Concept*Concept] is present in the file `Relations.json`. This bug bars the road to using the Atlas. 
@Michiel-s do you have any idea what is going on? We might look at this issue together, using skype.

**Comment by hanjoosten** [comment]
There are also other ways to reproduce. It seems that when the atlas is enabled, any script that has has `CLASSIFY` statements run into this.

**Comment by Michiel-s** [comment]
I know (part of) the fix. Give me a momeng

**Comment by hanjoosten** [comment]
That would be great!

**Comment by Michiel-s** [comment]
I've cherry picked a commit and pushed it to branch AmpersandTarski/Ampersand/RAP_issues#25.

Forcing relation declarations in population output was already needed for the new way of importing default population I was working on.

Could you check if this fixes the problem? Don't know what the `CLASSIFY` has to do with this.

**Comment by hanjoosten** [comment]
hahaha a Haskell fix! Congrats! It works great!
