### ISSUE TITLE
Cleanup student prototypes after 1 hour

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#256]
# What is the purpose: why do we need it?
Student prototypes are now generated and kept alive for eternity. We should remove them after a certain amount of time.

# How to accomplish the task
Add a scheduled task that looks for student prototypes older and remove this:

# List of subtasks

- [x] Add scheduler as a deployment?
- [x] Remove service, ingress, config file, deployment
- [ ] Remove dataset?

# What is the result?

**Comment by FreekOrdina** [comment]
CronJob

**Comment by Michiel-s** [comment]
I don't think this is a solution for this issue.

The deployment of student prototype include a Deployment, Service and Ingress. All of these need to be cleanup up.

The example above is about a max duration for attempt to run a Job. That is something else.

What we need is a CronJob that runs every hour, checks the time a student prototype deployment runs and if that exceeds an hour it cleanups up.

My experience is that a dedicated container with a shell script is needed to perform this action. The CronJob starts this container every hour.
