### ISSUE TITLE
Build Docker images RAP and student-prototype

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#265]
# What is the purpose: why do we need it?
Updates have been made for RAP (creates student-prototype deployment on Kubernetes) and rap-student-prototype (entrypoint for Kubernetes deployment)

# How to accomplish the task
Get access to Docker hub and build new images. Optionally we could do this with Github actions.

# List of subtasks

- [x] Get access to Docker Hub
- [ ] Create Github actions stage
- [ ] Create new image RAP4 with Github pipeline
- [ ] Create new image rap-student-prototype with Github pipeline

# What is the result?

**Comment by Michiel-s** [comment]
Hi @FreekOrdina,

My Docker Hub account details are configured as secret on Github organization level. This can be used in action scripts for all repos.
See [configured secrets](https://github.com/organizations/AmpersandTarski/settings/secrets/actions)

Example of such usage in Action workflow for the prototype framework repo. See: https://github.com/AmpersandTarski/prototype/blob/main/.github/workflows/build-push-to-docker-hub.yml

Please note that
> Secrets and variables allow you to manage reusable configuration data. Secrets are encrypted and are used for sensitive data. [Learn more about encrypted secrets](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets). Variables are shown as plain text and are used for non-sensitive data. [Learn more about variables](https://docs.github.com/actions/learn-github-actions/variables).

> Anyone with collaborator access to the repositories with access to a secret or variable can use it for Actions. They are not passed to workflows that are triggered by a pull request from a fork.

> Organization secrets and variables cannot be used by private repositories with your plan.

**Comment by Michiel-s** [comment]
To give you (and others) to push to Docker hub locally, we need to add your account to the Ampersand Tarski organization on Docker Hub. Please share your account details then I can add you to that list.


![Image](https://user-images.githubusercontent.com/7961582/231985082-a51d5143-9efa-4272-ba88-eadc34faa072.png)
