### ISSUE TITLE
RAP3 error messages come up

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#28]
The following error messages come up all the time: 
”maximum reruns exceeded for ExecEngine (rules with violations:SURscritContent)”
"DelAtom() expects 2 arguments, but you provided 10"
[Schermafdruk 2017-11-21 09.53.47.png.pdf](https://github.com/AmpersandTarski/RAP/files/1490635/Schermafdruk.2017-11-21.09.53.47.png.pdf)

**Comment by stefjoosten** [comment]
I have a hypothesis. I might have introduced the erroneous code as a result of introducing double quotes for atoms on October 17th, 2017. I think so as a result of inspecting the RAP3 code, searching for `DelAtom`. I found a possible culprit in `Scripts.adl`.

If I am right,, I should not be able to delete a script without getting this error. Let me do the experiment.

**Comment by EstherHageraats** [comment]
exec engine - error is gone. 
del atom error is still there, but that is recorded in issues #30
