### ISSUE TITLE
RAP3 gives error on _SESSION that RAP3 replaced itself

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#29]
Clicking ”beware to save…” makes RAP3 change the line of code that declares the interface: `INTERFACE Overview: ’_SESSION’ cRud` becomes 
`INTERFACE Overview : '0dfd0423033e72c38174b87ca9fa389e' cRud `
And after pressing ”compile” this changed code results in an errormessage (see picture)
[Schermafdruk 2017-11-21 09.49.40.png.pdf](https://github.com/AmpersandTarski/RAP/files/1490658/Schermafdruk.2017-11-21.09.49.40.png.pdf)

**Comment by stefjoosten** [comment]
This is the same issue as AmpersandTarski/Ampersand#707. I have assigned it to @Michiel-s and @hidde-jan, hoping they can solve this. On this location I am closing the issue because it duplicates an existing issue.
