### ISSUE TITLE
Select-all and copy in new script results in error

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#31]
Actions: 
- Cmd-A in the editor with existing script
- Cmd-C in the editor
- new script
- Cmd V in the editor

Result:
In the editor, the script is visible only once.
but the following rule violation comes up: Each ScriptContent may only have one Script in the relation content. In the details of the violation the code is visible twice.

There is no such problem when copying a script from another source (e.g. Gitbookpage)

**Comment by LloydRutledge** [comment]
is part of https://github.com/AmpersandTarski/RAP/issues/70

**Comment by stefjoosten** [comment]
The code for RAP has been changed in commit 1dbc728. So it will be fixed in the next release, which appears after the student-run of 2019 has finished.
