### ISSUE TITLE
Request with regard to tutorial

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#33]
The system "enrollment" that is used as an example system in the tutorial needs to be made available as an executable. 
Second, the file enrollment.adl needs to be made available as downloadable file.

**Comment by EstherHageraats** [comment]
Executable is available now and link refers to is.

**Comment by EstherHageraats** [comment]
this about the link from https://ampersandtarski.gitbooks.io/documentation/content/tutorial/what-is-an-information-system.html to the compiled version of the enrollement application.
The link is broken again, internal server error 500, file not found.
Probably a new release of RAP3?

I upgrade this issue to a bug: it is easily fixed I think, but students need it now. So please solve quickly.

**Comment by hanjoosten** [comment]
It seems to me that the link is correct. However, the Enrolment app doesn't seem to be deployed correctly. Maybe @hidde-jan and I could work together to see what we can do.

**Comment by hanjoosten** [comment]
The enrollment.adl file can be downloaded from the master branch at any time: [https://github.com/AmpersandTarski/RAP/blob/master/Demos/Enroll/Enrollment.adl](https://github.com/AmpersandTarski/RAP/blob/master/Demos/Enroll/Enrollment.adl)

**Comment by stefjoosten** [comment]
Enroll works in the development environment. When released, it will work with URL http://rap.cs.ou.nl/Enroll.
