### ISSUE TITLE
Unable to use Prototype on https after first generation

### ISSUE THREAD

**Issue by KlaasDijkstraOrdina** [AmpersandTarski/RAP#339]
#### De situatie
Followed RAP4 tutorial and generated prototype from example code. Then pressed 'Open prototype' button.

#### Wat er gebeurde er en wat had je verwacht?
Could not visit Prototype on https, because of invalid https cert (Kubernetes Ingress Controller Fake Certificate).
Works on http, but I had to change it manually in the addressbar (no 'Continue anyway' button). Some beginners might not understand how to do this / what to do.

Might be solved by linking to http instead of https first time?

Note: on codechange and 2nd time open it worked on https (LetsEncrypt cert)

**Comment by FranSlot** [comment]
Due to wait times when first creating the student container it can take some time before let's encrypt issues a certificate. Will be fixed in #316.
