### ISSUE TITLE
Cannot make a new user account for selected User Identifiers

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#34]
I have tried to make a user account with just a part of my own name. I would expect a green "+" somewhere to allow me to make a new user. However, this is obscured by the front-end, who is trying to help me spell my own name: 
![afbeelding](https://user-images.githubusercontent.com/275768/33237569-9d409932-d277-11e7-8fd5-99542ffcc8d4.png)

Everything works fine if I use a name that does not occur as a prefix of an existing user:
![afbeelding](https://user-images.githubusercontent.com/275768/33237572-ce284004-d277-11e7-950b-5168cdd41083.png)

@RieksJ any inspiration on this? You can reproduce this behaviour on rap.cs.ou.nl/RAP3/

**Comment by RieksJ** [comment]
This behaviour is intended, but your use case is valid. This is indeed front-end stuff that I cannot fix. I've shown it to @Michiel-s and transfer the ticket.

**Comment by stefjoosten** [comment]
I discussed this with Michiel. It is a small change in `static/templates/views/ATOMIC_object.html`, which I will try to do myself.

**Comment by stefjoosten** [comment]
This issue seems to have gone away. I cannot reproduce it in the current version.
