### ISSUE TITLE
Prototype does not work on first visit (you get red button + install fails first time)

### ISSUE THREAD

**Issue by KlaasDijkstraOrdina** [AmpersandTarski/RAP#340]
#### De situatie
As a new user, when opening the Prototype for the first time I got the Red button "Reinstall Application". I found this a bit confusing.

#### Wat er gebeurde er en wat had je verwacht?
Also Reinstall did not work on the first attempt (see screenshot), but did on the 2nd.

At least some extra info on this page would be helpful. Or automatic install if not found, if possible.

#### Screenshot / Video
![Open prototype error](https://github.com/AmpersandTarski/RAP/assets/153180202/28b82beb-d226-4761-9f57-590a766479f8)

**Comment by FranSlot** [comment]
This was fixed by updating the prototype version.
