### ISSUE TITLE
Bug mysql database after creation prototype

### ISSUE THREAD

**Issue by lucsomers101** [AmpersandTarski/RAP#356]

**Comment by lucsomers101** [comment]
During creation of a prototype when you made an account with the name aa-123 it gives the following error.

![Image](https://github.com/AmpersandTarski/RAP/assets/144434022/1e8e62c8-8e0d-433d-923a-874c658f5d54)

**Comment by lucsomers101** [comment]
following file contains the trace of the error message above:

[trace mysql name error'.txt](https://github.com/AmpersandTarski/RAP/files/14181510/trace.mysql.name.error.txt)

**Comment by FranSlot** [comment]
> This issue is comparable with issue #331 . In both cases the user writes her name as a string. Then, there is a function that maps that string to a name of a table/database. In issue #331 that mapping was done by using the `lowercase` function. Clearly, this isn't enough. `-` isn't allowed and probably several other characters aren't allowed as name. Also, what happens if a user types a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long name?
> 
> To solve this issue, the requirements of the mapping should be considered. Then, it will be quite straightforward to solve it, I guess.

Actually hyphens are allowed in SQL strings but the string should be put within backticks `` ` ``. As of now the prototype project does not do this causing problems with hyphens.

**Comment by FranSlot** [comment]
After call with @hanjoosten decided to make a function in RAP to properly sanitize the name.
