### ISSUE TITLE
Geen prototype op basis van het tutorial

### ISSUE THREAD

**Issue by EricaRietveld** [AmpersandTarski/RAP#361]
#### De situatie
Ik heb cf. instuctie de code uit de tutorial in het RAP 4 scherm gekopieerd, en laten complileren.

#### Wat er gebeurde er en wat had je verwacht?
Message: This script of Enrollment contains no type errors. OK
Functional specs, doc gedownload OK
Click Prototype: foutboodschap.
[unable to decode "/var/www/data/scripts/834719305/Script_5bd0cd19-a6dc-4537-bc36-3f07e81bfd7b/ScriptVersion_cfacb130-08d3-40b5-8b11-abe08044ea44/student-manifest-834719305.yaml": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string, unable to decode "/var/www/data/scripts/834719305/Script_5bd0cd19-a6dc-4537-bc36-3f07e81bfd7b/ScriptVersion_cfacb130-08d3-40b5-8b11-abe08044ea44/student-manifest-834719305.yaml": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.name of type string]
Error from server (BadRequest): error when creating "/var/www/data/scripts/834719305/Script_5bd0cd19-a6dc-4537-bc36-3f07e81bfd7b/ScriptVersion_cfacb130-08d3-40b5-8b11-abe08044ea44/student-manifest-834719305.yaml": Ingress in version "v1" cannot be handled as a Ingress: json: cannot unmarshal number into Go struct field IngressServiceBackend.spec.rules.http.paths.backend.service.name of type string

#### Stappen om dit te reproduceren
1. Zie bovenstaande

#### Screenshot / Video
![afbeelding](https://github.com/AmpersandTarski/RAP/assets/60888560/3a643714-f295-49f6-9703-f9ac113d0118)

#### Context / Source van ampersand script
Script uit de Tutorial. 
Context: afstudeerwerk Bachelor Informatica, OU. Verzoek van Stef Joosten om dit probleem hier te melden.

**Comment by stefjoosten** [comment]
@lucsomers101 , @FranSlot , bijgaande tekst kan een licht werpen op de vraag waarom de OU-RAP uit de lucht is. Er lijkt iets met de ingress mis te zijn. Kunnen jullie een diagnose maken?

**Comment by lucsomers101** [comment]
Concluded that the error occurs when users log in with the number combination 834719305 the error also occurs when using this: 8347 user account. Problem is under further investigation.

User uses name instead of number as a temporary workaround

**Comment by hanjoosten** [comment]
This seems related to a previous issue with the allowed characters in the name of a student. See [this comment](https://github.com/AmpersandTarski/RAP/issues/338#issuecomment-1855581344) in that issue.

**Comment by EricaRietveld** [comment]
Hoi Luc,

Immiddels ook het antwoord van Han Joosten gelezen. Dit gaat steeds over
problemen met het prototype.
Zijn tekst op Github: "There should be a mapping from the name to the
subdomain. For instance, apply a function that removes all characters that
are not allowed, or (even better?) substitute them with an allowed
character." Ik heb geen idee wat ik daarmee moet doen of zou kunnen.

Hij reageerde op een probleem met een username waarin ook de volgende
instructie was beschreven: "a lowercase RFC 1123 subdomain must consist of
lower case alphanumeric characters, '-' or '.', and must start and end with
an alphanumeric character". Ik heb nog een username metaleen lowercase
aangemaakt, maar dat veranderde mijn probleem niet.

Overigens gaat het probleem op Github over een niet werkend prototype, dat
hadden we al opgelost; het werkte voor het tutorial-script.
De foutmelding m.b.t. mijn eigen script betreft compilatie. Ik hoop dat
ergens beschreven is welk karakter UnexpectedChar '\8746' betreft.
Als gezegd: ik heb al gepoogd om door alle details van mijn script te
lopen, niets gevonden, maar de foutmelding helpt ook niet. Kan daardoor nu
niet meer verder.

Alvast dank voor enige vorm van hulp of doorverwijzing!
Prettig weekend,
Erica

Op vr 8 mrt 2024 om 12:24 schreef Luc Somers ***@***.***>:

**Comment by hanjoosten** [comment]
Dag Erica, 
Het is handiger om [deze discussie](https://github.com/AmpersandTarski/RAP/issues/361) direct op github te doen, i.p.v. via de mail. Alle commentaar die daar wordt neergezet, krijgt iedere volger van dat issue te zien. Maar dat terzijde. 

Ik weet niet precies waar je tegenaan loopt, maar ik zie twee clues, die in dezelfde richting wijzen:

1) De error melding in het plaatje zegt iets over niet kunnen decoden van een bestand.
2) Jij hebt het over een `UnexpectedChar '\8746'` foutmelding. Die heb ik nog niet gezien in dit log. Wellicht dat je die foutmelding hier kan toevoegen?

Dat doet mij vermoeden dat er iets mis is met het bestand dat je aanbied. Dit soort fouten kunnen onder andere ontstaan doordat je met cut/paste een lap tekst uit een word bestand haalt. Dan kan er wat [mis gaan met verschillende encodings](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/).  

Maar voor hetzelfde geld is er heel wat anders aan de hand. Ik probeer slechts mee te denken.

**Comment by EricaRietveld** [comment]
Dankjewel voor je reactie, Han. Ik zal maandag verder gaan, en dan idd ook
Github gebruiken.

Prettig weekend,
Erica

Op vr 8 mrt 2024 om 20:36 schreef Han Joosten ***@***.***>

**Comment by lucsomers101** [comment]
Concluded that name starts with a letter like the name: t8887 error does not occur.
