### ISSUE TITLE
Beveiligings issues

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#371]
#### De situatie
Op https://basisbeveiliging.nl/report/NL/education_university/5646 staan actuele beveiligings-issues met betrekking tot de OU. Een flink deel daarvan betreft RAP. Daar moeten we wat mee, omdat ze de statistiek van de hele OU onderuit halen...

#### Wat er gebeurde er en wat had je verwacht?
Ik kreeg een e-mail van de OU of ik er wat aan kan doen....

#### Stappen om dit te reproduceren
1. Navigeer naar https://basisbeveiliging.nl/report/NL/education_university/5646
2. kijk naar alle URL's waar rap in voorkomt.

#### Screenshot / Video
![afbeelding](https://github.com/AmpersandTarski/RAP/assets/275768/b01174df-dcda-48a4-965a-ed93d9ba2bcd)

Hier is een dump van het volledige rapport:
[basisbeveiliging_risk_summary_table_all_2024-04-16T00 00 00+02 00_.csv](https://github.com/AmpersandTarski/RAP/files/14994660/basisbeveiliging_risk_summary_table_all_2024-04-16T00.00.00%2B02.00_.csv)

**Comment by hanjoosten** [comment]
Een uitgebreide toelichting is te vinden in het [rapport voor rap.cs.ou.nl](https://basisbeveiliging.nl/report/NL/education_university/5646?tab=report_detail&filter_url=rap.cs.ou.nl)

**Comment by lucsomers101** [comment]
Update: Om dit op te lossen hebben we een wildcard certificate nodig. Dit zorgt ervoor dat er 1 certificaat is voor alle *.tarski of ou domeinen. Om dit voor elkaar te krijgen hebben we een speciaal account nodig op de azure omgeving die we in de pipeline kunnen gebruiken alleen zijn de rechte die hiervoor nodig zijn niet helemaal duidelijk.

Link naar website met informatie over deze actie: [Link](https://cert-manager.io/docs/configuration/acme/dns01/azuredns/ )

**Comment by stefjoosten** [comment]
Er zijn twee certificaten geplaatst: één voor *.rap.cs.ou.nl en één voor *.staging.rap.cs.ou.nl. Hiermee zijn de ergste problemen verholpen. Er zijn nog wel kleinere beveiligingsproblemen om te verhelpen...
