### ISSUE TITLE
RAP3 does not deploy automatically

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#38]
# Reproducing the flaw
To install RAP3 on a server, go to that server, get the file ``https://github.com/AmpersandTarski/RAP/blob/master/docker-compose.yml`` and run docker-compose up -d``. I did that with the sandbox server ``52.232.97.91``, which is an Ubuntu server.

(The docker code for building RAP3 lives in ``https://github.com/AmpersandTarski/RAP/blob/master/RAP3/Dockerfile``. The image resides in ``ampersandtarski/rap3`` on docker hub.)

I expected  ``52.232.97.91/RAP3`` to work just like that. However, this did not work. The machine was stuck.

**Comment by stefjoosten** [comment]
# Analysis
The ``docker-compose.yml`` installs volumes:
```
    volumes:
      - ./volumes/log:/var/www/html/RAP3/log
      - ./volumes/scripts:/var/www/html/RAP3/scripts
```
On the server, I can see that the volumes are made on ``/var/www/html/RAP3`` with owner root. Somehow, I cannot manage to tell (in ``RAP3/Dockerfile``) that ownership of these directories should be transferred to ``www-data``. I've tried things, but without much luck so far.

**Comment by hanjoosten** [comment]
Did some google-ing. Could this help: https://docs.docker.com/engine/security/userns-remap/ ?

**Comment by stefjoosten** [comment]
I'm closing this issue because we seem to be pretty much on track with the docker stuff...
