### ISSUE TITLE
No Connection error

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#383]
#### Wat er gebeurde er en wat had je verwacht?
Als ik mijn prototype start op `staging.rap.ou.cs.nl` krijg ik dit te zien: 
<img width="888" alt="afbeelding" src="https://github.com/user-attachments/assets/c6e4cb8e-7627-4fde-9ed8-279621adcb05">

Als ik mijn prototype start op `rap.ou.cs.nl` krijg ik dit te zien: 
<img width="680" alt="afbeelding" src="https://github.com/user-attachments/assets/6409c74d-4720-4765-8be3-3fcebc0af3ac">
Ik had verwacht dat ik mijn prototype te zien zou krijgen op de URL `stefj.rap.ou.cs.nl`. Vanochtend lukte dat nog wel.

Wanneer ik probeer via PhpMyAdmin naar de database te kijken krijg ik dit te zien:
<img width="1063" alt="afbeelding" src="https://github.com/user-attachments/assets/02ac21a0-c88c-4ebb-b712-7dc7d9e17a3c">

Vanochtend is een wildcard certificaat verkregen voor `*.staging.rap.cs.ou.nl` en dit heeft gewerkt. Een certificaat voor `*.rap.cs.ou.nl` was al eerder aanwezig. Ik weet niet of dit ermee te maken heeft. Het lijkt er los van te staan.

**Comment by stefjoosten** [comment]
Very odd. All of a sudden it works again. Something to do with the cloud infrastructure? I'm leaving it open for a few days to see if this recurs.

**Comment by hanjoosten** [comment]
Dit zou te maken hebben met overbelasting of onderhoud. Ik weet van geen onderhoud. Overbelasting zou het onderzoeken waard zijn. Zie voor details https://kinsta.com/nl/blog/http-error-503/
