### ISSUE TITLE
Secured server connection?

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#39]
A student has expressed concern because his case study has "non disclosure agreement" sensitive information that they in principle cannot set on an insecure server. My advice was to install RAP3 locally (safer than any online server) and/or to "anonymize' the data on the server. Perhaps we could package the OU RAP3 server within a broader package on the OU server that requires OU login. If it's important enough - I'll see how much further discussion there is on the course.

**Comment by stefjoosten** [comment]
This is definitely an issue. We must look into it. The solution is described in https://docs.docker.com/engine/security/certificates/.

**Comment by stefjoosten** [comment]
I'm closing this issue, because the security concerns are treated in issue #20.
