### ISSUE TITLE
RAP3 ERROR: No prototype generated because of rule violations. message.

### ISSUE THREAD

**Issue by dartheide** [AmpersandTarski/RAP#40]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
http://rap.cs.ou.nl

#### Wat ik verwachtte
Een prototype
#### Wat er gebeurde
Geen prototype, en geen foutmelding in RAP3

#### Stappen om dit te reproduceren
1. Eerst compileren, daarna prototype aanmaken en bij een rule violations verschijnt er geen melding dat er er geen prototype is aangemaakt. 
2. Ik kan de melding in mijn eigen ampersand omgeving reproduceren maar RAP3 geeft geen melding.

#### Screenshot / Video
ERROR: No prototype generated because of rule violations.
ERROR: Service 'prototype' failed to build: The command '/bin/sh -c ampersand --proto=/var/www/html /src/$ADL_FILE --verbose  && mkdir -p /var/www/html/log  && chown -R www-data:www-data /var/www/html  && sed -i "s|.*Config::set.*dbHost.*|Config::set('dbHost', 'mysqlDatabase', getenv('AMPERSAND_DB_HOST'));|" /var/www/html/localSettings.php' returned a non-zero code: 40

#### Context / Source van ampersand script
Spreekt voor zich.

**Comment by stefjoosten** [comment]
Is verholpen. Helaas is dit issue niet reproduceerbaar, zodat het verhelpen ervan niet getest is. Dit gaat mee met de volgende release
