### ISSUE TITLE
2002: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

### ISSUE THREAD

**Issue by dartheide** [AmpersandTarski/RAP#42]
URL http://rap.cs.ou.nl/RAP3/#/

Please contact the application administrator for more information.

Zie de melding RAP3, het is ook niet mogelijk om in te loggen.

<img width="1280" alt="screen shot 2018-01-02 at 14 37 34" src="https://user-images.githubusercontent.com/2808100/34485465-2697e922-efcb-11e7-8cba-631110a5e635.png">

**Comment by hanjoosten** [comment]
Dit ziet er uit als een netwerk probleem. De database is onbereikbaar. @LloydRutledge zou wel eens bezig kunnen zijn om de applicatie te herstellen, nadat de harde schijf is volgelopen. Zie ook issue #41

**Comment by bram-joosten** [comment]
Ik heb de machine herstart. Kun je kijken of het verholpen is? Als het inderdaad het vollopen van de database is, dan is het waarschijnlijk niet verholpen...

**Comment by dartheide** [comment]
Is opgelost, ik kan er weer in.
