### ISSUE TITLE
RAP3: MySQL error: Disk full, no space left on device

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#43]
This error occured running RAP3 from commit fc8782f on Dec 26th, 2017.

http://rap.cs.ou.nl/RAP3

# Wat ik verwachtte

Dat de schijf niet vol raakt, zodat studenten kunnen blijven werken.

# Wat er gebeurde

De schrijf zit vol waardoor RAP3 niet meer kan draaien waardoor geen enkele student die kan gebruiken voor hun opdracht. Stef heeft een reboot gedaan die het even oplost maar dan kwam hetzelfde probleem snel weer terug.

# Stappen om dit te reproduceren
 
Gewoon naar http://rap.cs.ou.nl/RAP3 gaan. Eventueel moet je een nieuwe script proberen te maken.

# Screenshot / Video

![image](https://user-images.githubusercontent.com/1098321/34563601-7a68e810-f153-11e7-9e4c-45e5c8f8beb6.png)

Vele studenten meden deze nu, t/m donderdag. Dus voor alle studenten nu een showstopper.

Stef, korte termijn oplossing dat alleen jij kan is de bestanden te zippen of verplaatsen. Ik kan die zien maar niks ermee doen.

Mid-termijn oplossing is dat ik onze servicedesk heb gevraagd om meer schrijfruimte te regelen. Misschien is die de hele oplossing. Vorig jaar met RAP2 heeft een resource-vergroting dergelijke problemen flink minder vak gemaakt, maar was niet opgelost.

Nog een deel-oplossing?: Helpt het als we de studenten verzoeken om onnodige en niet-gebruikten scripts te wissen van hun accounts? Dat kan ik hun vragen maar alleen als het werkelijk helpt. Maakt deze actie meer ruimte op de schrijf? Worden bijhorende bestanden uit ./volume/scripts en ./volume/MySQL gewist?

Lange termijn oplossing: Dat de server bestanden zipt. Andere servers zippen de oude log-bestanden zelf en automatisch. Dus alle logs behalve degene die nu nog logberichten krijgt. Kan RAP3 ook alle script-bestanden in ./volume/scripts altijd zippen bij opslaan en unzippen bij lezen?

En wat is het verhaal met ./volumen/MySQL ? Misschien kan Stef kijken hoeveel ruimte MySQL/ gebruikt in vergelijking met scripts/. Ik kan die zelf niet inkijken. Kunnen we die zippen? Zijn er nog andere manieren op zuinig te zijn met MySQL bestanden?

Als ik meer informatie krijg over de grote van de directories en bestanden dan zet ik die hier.

Han, bedankt voor je bestand-grote tips in je e-mail. Die waren nuttig voor deze analyse.

**Comment by hanjoosten** [comment]
@LloydRutledge Het helpt niet om de studenten te vragen om scripts te verwijderen. Alles wordt opgeslagen, en ze kunnen zelf niets wissen. We moeten op @stefjoosten wachten om te kijken naar de bestanden en een en ander te verwijderen. Daarnaast is het natuurlijk ook nuttig om in te richten dat er monitoring komt op de hoeveelheid schijfruimte. Geen enkele applicatie kan er tegen dat de schijfruimte vol raakt. Ook RAP3 niet.

**Comment by LloydRutledge** [comment]
Bedankt, @hanjoosten. Ik bekijk hoeveel ruimte we van de OU nu hebben en dan hoeveel we krijgen, en tot hoever die redelijk zijn in vergelijking met een "typisch" server, en voor ons gebruik. En dan hoe snel en hoe groet log/ scripts/ en MySQL/ worden. Een volle schrijfruimte is niet uit te sluiten. Maar het kan helpen om efficiënter te zijn als we zien dat bepaalde schrijfgebruik snel oploopt naar de bovengrens. Als het een probleem blijft toch met redelijk schijfruimten dan vind ik waar het het ergste is en maak ik een voorstel voor een oplossing die erop gericht is.

**Comment by LloydRutledge** [comment]
@stefjoosten zet RAP3 terug online als je terug bent a.u.b. En a.u.b. maak ruimte als we die niet al van ICT gekregen hebben. En kan je met leestoestemming geven voor de hele directory tree? En misschien ook schrijf(wis) toestemming? Met de later kan ik dan zelf zippen.  Maar belangrijker: met leestoestemming kan ik "du -s" enz. gebruiken om de schijfruimte te blijven meten en subdirectories te vergelijken.

**Comment by LloydRutledge** [comment]
De OU RAP3 server is nu terug online. En met 5GB meer ruimte. Er kan ook later tot 6,7GB meer komen. Ik blijf peilen hoewel er gemiddeld gebruikt wordt: per student, per script, en over de drie subdirectories.

**Comment by hanjoosten** [comment]
Super. Het zou interessant zijn om te kijken hoe dit zich in de tijd gedraagt. Iedere keer als een student een prototype genereert, wordt daar een nieuwe directory voor aangemaakt (binnen scriptversion). Daarnaast wordt er in de database voor dat prototype ook een nieuw schema gegenereerd, de eerste keer dat de student daadwerkelijk dat prototype activeert. Hierdoor kan het aantal schema's in de database ook oplopen. Ik vraag me af of dat heel veel gebeurt. Dat zal per student heel verschillend kunnen zijn. Ook vraag ik me af of zo'n schema veel ruimte inneemt. Het zou best wel eens kunnen dat mariaDB dat op een efficiënte manier doet. Ik weet niet hoe je dat precies zou kunnen meten. Ik verwacht dat MariaDB ergens een directory heeft waar de databasebestanden worden geadministreerd.

**Comment by stefjoosten** [comment]
This issue has been resolved by assigning more disk space. Alas, this has not removed the cause of this problem, which is addressed in issue #52. So I am closing this issue here and proceed with issue #52.
