### ISSUE TITLE
RAP3 instructies voor file purge bij volle schijf?

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#45]
Wat moet ik of een andere serverbeheerder doen om bestanden te wissen als korte termijn oplossing voor een volle schijf? Ik neem aan dat er bepaalde bestanden zijn die weg kunnen. En die kunnen we gewoon wissen, en zo mogelijke de originele archiveren op een andere schijf. En moeten we ook via MySQL data tabellen purgen? Stef en Gerard hebben iets dergelijks vorige jaar gedaan een paar keer met RAP2.

Ik neem aan bijvoorbeeld dat alle log-bestand misbaar zijn behalve de huidige. Die kunnen dan gewoon verplaatst zijn. De gebruikers zullen niks merken.

Ik neem aan dat we de script-bestanden in ./scripts/ ook kunnen verplaatsen. Blijft dan RAP3 gewoon online een draaiend? De gebruikers zullen zien dat hun oude scripts niet meer in het systeem zijn. Die zijn al gewaarschuwd dat ze hun benodigde code op eigen systemen moeten opslaan.

Is dat dan het enige probleempje voor de gebruiker, dat hun scripts weg zijn? Blijven hun accounts gewoon intact zodat je kunnen blijven inloggen? Moet dan gebruikersgericht subdirectories in ./scripts/ blijven hoewel nu leeg? Of kan de hele subdirectory tree onder ./scripts helemaal weg?

En kunnen we ruimte maken in ./MySQL/ door bestanden en subdirectories te verplaatsen? Of moeten we die helemaal niet aanraken? Of kunnen we via MySQL die ruimen.

Natuurlijk is de echte oplossing om meer ruimte op de server te maken. Dat moet binnenkort gebeuren. Maar als die verhoging later ook te weinig wordt dan duurt het minstens zo lang om meer ruimte te krijgen, of krijgen we die moeilijker of niet. In ieder geval zal het een tijdje duren, waarin deze file purge en belangrijk korte termijn oplossing wordt waardoor de studenten kunnen blijven werken.

En daarna moet RAP3 gerestart worden of is het genoeg dat er dan ruimte op de schrijf is?

Hopelijk als Stef weer online is kan hij deze purge uitvoeren, en dan ook de restart die nu nodig in vanwege de PHP probleem. In ieder geval misschien moet hij of ik die in de komende weken weer doen dus als er instructies of tips komen dan dank je wel!

-Lloyd

**Comment by stefjoosten** [comment]
Hoi Lloyd, ik zit ernaar te kijken. Ik heb de machine gereboot, maar hij komt nog niet op.
De tijd dat hij normaliter nodig heeft om te rebooten is allang verstreken.
Misschien heeft dat ook te maken met de volgelopen schijf. Als hij niet herstart vanwege de volgelopen schijf, dan moeten we ICTS erbij halen. Wil jij morgenochtend meteen bellen?

**Comment by stefjoosten** [comment]
Hoever was je met jouw space-monitor?

**Comment by stefjoosten** [comment]
Quick fix:
Lloyd, tot het moment dat we de ou server in de lucht hebben, kunnen studenten uitwijken naar http://ampersand.tarski.nl/RAP3.
