### ISSUE TITLE
Wachtwoord doorsturen en/of herstellen

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#46]
Studenten vergeten soms de wachtwoorden voor hun accounts. Kan RAP3 een of beide van de functionaliteiten kringen voor wachtwoorden?:

- Doorsturen?
- Herstellen?

Huidige oplossing is dat de student een nieuw account maakt. Die kan een administrator ook verzoeken om zijn account te wissen, waardoor ze een nieuw account kan maken met hetzelfde wachtwoord. Maar dan is de student zijn of haar oude scripts kwijt, maar dan weten ze dat RAP3 geen scriptopslagplek is.

**Comment by stefjoosten** [comment]
Hi Lloyd, I showed you how you can interfere with passwords, so now you can resolve the most pressing issues. The next step will be to rely on an identity provider (such as the OU, LinkedIn, Github, etc.). That will free us from any password administration (and the privacy risks associated with it.).
