### ISSUE TITLE
Conceptueel model RAP3 systeemconcepten

### ISSUE THREAD

**Issue by jeroenvelzeboer** [AmpersandTarski/RAP#49]
#### Versie (in de CLI:  >  ampersand --version)
RAP3

#### Wat ik verwachtte
Momenteel heb ik een script gebouwd met daarin alle concepten en 28 relaties. Wanneer ik dit script compile en een diagnose uitvoer dan zie ik dat het script geen fouten signaleert, kortom: het script werkt naar behoren. Echter op het moment dat ik zowel in het diagnose document als in de functionele specificatie kijk naar het conceptuele model dan zie ik een conceptueel model van de systeemconcepten (Systemspecific: role, session, datetime) en geen conceptueel model van de door ons ingevoerde concepten.

#### Wat er gebeurde
Ik krijg enkel een conceptueel model van de systeem concepten te zien.

#### Stappen om dit te reproduceren
1. alle bedrijfsregels verwijderd 
2. script met enkel de concepten gerunt
3. script met zowel concepten als relaties gerunt
4. 

#### Screenshot / Video
https://prnt.sc/i4ykxi
https://prnt.sc/i4ylzz
https://www.scribd.com/document/369892653/Version2018-01-24T155409

**Comment by jeroenvelzeboer** [comment]
CONTEXT Afstuderen IN DUTCH
META "authors" "Jürgen Esselink, Rosanne Hubers, Karin van der Velde, Jeroen Velzeboer"

{-------------------------------------------------------------------------------------------------------------}
-- Concepten
CONCEPT AfstudeerStage "Periode waarin de student aan dient te tonen dat zijn kennis van het gewenste Hbo-niveau is en dat hij dit kan toepassen binnen een stage-organisatie"
CONCEPT AfstudeerOpdracht "Opdracht die een student binnen een bedrijf uitvoert tijdens zijn stage om aan te tonen dat hij een bepaald niveau heeft"
CONCEPT AfstudeerStagecoordinator "Keurt afstudeeropdrachten in beginfase en kent assessoren toe aan de student"
CONCEPT Online_Stagesysteem "Informatiesysteem waarin externe bedrijven stageopdrachten kunnen plaatsen"
CONCEPT Student "Persoon die onderwijs volgt"
CONCEPT DocentBegeleider "Een docent die de student begeleidt tijdens diens afstudeerstageperiode"
CONCEPT BedrijfsBegeleider "Een medewerker van het StageBedrijf, welke de student begeleidt tijdens zijn afstudeerstage"
CONCEPT StageBedrijf "Organisatie waar de student zijn afstudeerstage uitvoert."
CONCEPT Assessor "Docent die o.a. verantwoordelijk is voor de eindbeoordeling van de afstudeerstage"
CONCEPT Plan_van_aanpak "Plan waarin de student het project plant en de scope van zijn onderzoek vaststelt"
CONCEPT StageVerslag "Door de student geschreven verslag met daarin de conclusies en procesinformatie t.a.v. de stageperiode"
CONCEPT BedrijfsBezoek "Moment welke twee keer gedurende de afstudeerstage voorkomt. De docentbegeleider visiteert de student en BedrijfsBegeleider op locatie van het StageBedrijf om over de voortgang van het project te spreken"
CONCEPT DagenVerantwoording "Formulier waarop de student verantwoord hoeveel stagedagen hij heeft gemaakt en welke hij bij de assessoren inlevert"
CONCEPT Examenkamer "Afdeling die de student al dan niet fiat geeft om zijn afstudeerstage te mogen starten"
CONCEPT Administratie "Afdeling die alle formele beoordelingsformulieren aangaande de afstudeerstage archiveert"
CONCEPT Kritische_Zelfreflectie "Formulier met daarop door de student genoteerde persoonlijke ontwikkelpunten waar hij tijdens de stage aan gaat werken"
CONCEPT Externe_Deskundige "Onafhankelijk persoon van buiten de onderwijsorganisatie die o.a. verantwoordelijk is voor de eindbeoordeling van de afstudeerstage"
CONCEPT Assessment "Moment in de laatste fase van de afstudeerperiode waarin de eindbeoordeling van de student tot stand komt"
CONCEPT Medewerker_AfstudeerBedrijf "Een persoon die in dienst is bij het afstudeerbedrijf"
CONCEPT Documenten " Aan het afstudeerproces gerelateerde documenten "
CONCEPT Vorig_Semester "De resultaten uit het aan de afstudeerstage voorafgaande semesters "
CONCEPT Kenmerk_AfstudeerOpdracht "Een afstudeeropdracht heeft meerdere kenmerken"
CONCEPT Kenmerk_StageBedrijf "Een stagebedrijf heeft meerdere kenmerken"
CONCEPT Kenmerk_Bedrijfsbegeleider "Een bedrijfsbegeleider heeft meerdere kenmerken"


{-------------------------------------------------------------------------------------------------------------}
-- Relaties omschrijving
{-Relatie 1: Een Student maakt een Plan_van_aanpak-}
{-Relatie 2: Een DocentBegeleider keurt het Plan_van_aanpak-}
{-Relatie 3: Een Student maakt een StageVerslag-}
{-Relatie 4: Een Assessor keurt het StageVerslag-}
{-Relatie 5: Een Student dient een DagenVerantwoording in-}
{-Relatie 6: Een Assessor keurt de DagenVerantwoording-}
{-Relatie 7: Een Student voert een AfstudeerStage uit-}
{-Relatie 8: Een Student voert een AfstudeerOpdracht uit-}
{-Relatie 9: Een AfstudeerStagecoordinator keurt een AfstudeerOpdracht-}
{-Relatie 10: Een AfstudeerStagecoordinator wijst een Assessor toe-}
{-Relatie 11: Een Assessor wordt gekoppeld aan een Student-}
{-Relatie 12: Een Online_Stagesysteem biedt AfstudeerOpdrachten aan-}
{-Relatie 13: Een DocentBegeleider begeleidt een Student -}
{-Relatie 14: Een BedrijfsBegeleider begeleidt een Student-}
{-Relatie 15: Een BedrijfsBegeleider werkt bij het StageBedrijf-}
{-Relatie 16: Een DocentBegeleider doet BedrijfsBezoek -}
{-Relatie 17: Een Examenkamer verleent de Student toestemming-}
{-Relatie 18: De Administratie archiveert Documenten-}
{-Relatie 19: Een Student vult een Kritische_Zelfreflectie in-}
{-Relatie 20: Een Externe_Deskundige neemt een Assessment af-}
{-Relatie 21: Een Examenkamer beoordeelt een Assessment -}
{-Relatie 22: Een Student doet een Assessment-}
{-Relatie 23: Een Medewerker_AfstudeerBedrijf werkt bij een StageBedrijf -}
{-Relatie 24: Een Student heeft resultaten uit het Vorig_Semester-}
{-Relatie 25: Een AfstudeerOpdracht heeft Kenmerk_AfstudeerOpdracht-}
{-Relatie 26: Een StageBedrijf heeft Kenmerk_StageBedrijf-}
{-Relatie 27: Een BedrijfsBegeleider heeft Kenmerk_BedrijfsBegeleider-}
{-Relatie 28: Een StageOpdracht hoort bij een StageBedrijf-}


{-------------------------------------------------------------------------------------------------------------}
-- Relaties declaratie
{- Relatie 1: Een Student maakt een Plan_van_aanpak-}
{-Een Student dient 1 en maximaal 1 Plan_van_aanpak in. -}
{-Een Plan_van_aanpak wordt door slechts 1 Student geschreven. -}
RELATION dientPlanVanAanpakin [Student*Plan_van_aanpak] [UNI, TOT, INJ]
MEANING "Een Student maakt een Plan_van_aanpak"
PURPOSE RELATION dientPlanVanAanpakin[Student*Plan_van_aanpak] {+Een student heeft een PVA gemaakt+}
POPULATION dientPlanVanAanpakin CONTAINS
[ ("Jeroen Velzeboer","PVA Jeroen");
  ("Rosanne Hubers","PVA Rosanne")
]

{-Relatie 2: Een DocentBegeleider keurt het Plan_van_aanpak-}
{-Een DocentBegeleider keurt 1 en minimaal 1 Plan_van_aanpak. -}
{-Een Plan_van_aanpak wordt door 1 en slechts 1 DocentBegeleider gekeurd. -}
RELATION keurtPlanVanAanpak [DocentBegeleider*Plan_van_aanpak] [UNI, TOT, INJ]
MEANING "Een DocentBegeleider keurt het Plan_van_aanpak"
PURPOSE RELATION keurtPlanVanAanpak [DocentBegeleider*Plan_van_aanpak] {+Het PVA wordt door de docentbegeleider beoordeeld op kwaliteit+}
POPULATION keurtPlanVanAanpak CONTAINS
[ ("Jurgen Esselink","PVA Jeroen");
  ("Karin Velde","PVA Rosanne")
]

 
 
{-Relatie 3: Een Student maakt een StageVerslag-}
{-Een Student maakt 1 en maximaal 1 StageVerslag. -}
{-Een StageVerslag wordt door 1 en slechts 1 student gemaakt. -}
RELATION maaktStageverslag [Student*StageVerslag] [UNI, TOT, INJ]
MEANING "Een Student maakt een StageVerslag"
PURPOSE RELATION maaktStageverslag [Student*StageVerslag] {+Het stageverslag is door de student gemaakt+}
POPULATION maaktStageverslag CONTAINS
[ ("Jeroen Velzeboer","Stageverslag Jeroen");
  ("Rosanne Hubers","Stageverslag Rosanne")
]

{-Relatie 4: Een Assessor keurt het StageVerslag-}
{-Een Assessor keurt 1 en minimaal 1 StageVerslag. -}
{-Een StageVerslag wordt door 1 en slechts 1 Assessor gekeurd. -}
RELATION keurtStageverslag [Assessor*StageVerslag] [UNI, TOT, INJ]
MEANING "Een Assessor keurt het StageVerslag"
PURPOSE RELATION keurtStageverslag [Assessor*StageVerslag] {+Het stageverslag wordt door de assessor gekeurd op kwaliteit+}
POPULATION keurtStageverslag CONTAINS
[ ("Dries Enden","Stageverslag Jeroen");
  ("Frits Vries","Stageverslag Rosanne")
]

{-Relatie 5: Een Student dient een DagenVerantwoording in-}
{-Een Student dient 1 en maximaal 1 Dagenverantwoording in. -}
{-Een Dagenverantwoording wordt door 1 en slechts 1 Student ingediend. -}
RELATION dientDagenverantwoordingin [Student*DagenVerantwoording] [UNI, TOT, INJ]
MEANING "Een Student dient een DagenVerantwoording in"
PURPOSE RELATION dientDagenverantwoordingin [Student*DagenVerantwoording] {+De student dient dagenverantwoording in om te bewijzen dat hij voldoende dagen heeft gemaakt+}
POPULATION dientDagenverantwoordingin CONTAINS
[ ("Jeroen Velzeboer","Dagenverantwoording Jeroen");
  ("Rosanne Hubers","Dagenverantwoording Rosanne")
]

{-Relatie 6: Een Assessor keurt de DagenVerantwoording-}
{-Een Assessor keurt 1 en minimaal 1 DagenVerantwoording. -}
{-Een DagenVerantwoording wordt door 1 en slechts 1 Assessor gekeurd.-}
RELATION keurtDagenverantwoording [Assessor*DagenVerantwoording] [UNI, TOT, INJ]
MEANING "Een Assessor keurt de DagenVerantwoording"
PURPOSE RELATION keurtDagenverantwoording [Assessor*DagenVerantwoording] {+De assessor stelt vast of de dagenverantwoording valide is en keurt deze+}
POPULATION keurtDagenverantwoording CONTAINS
[ ("Dries Enden","Dagenverantwoording Jeroen");
  ("Frits Vries","Dagenverantwoording Rosanne")
]

{-Relatie 7: Een Student voert een AfstudeerStage uit-}
{-Een Student doet 1 en maximaal 1 AfstudeerStage. -}
{-Een AfstudeerStage wordt gedaan door 1 en slechts 1 Student.-}
RELATION doetAfstudeerstage [Student*AfstudeerStage] [UNI, TOT, SUR]
MEANING "Een Student voert een AfstudeerStage uit"
PURPOSE RELATION doetAfstudeerstage [Student*AfstudeerStage] {+De student voert zijn afstudeerstage uit in een bepaalde periode+}
POPULATION doetAfstudeerstage CONTAINS
[ ("Jeroen Velzeboer","Periode VJ2018");
  ("Rosanne Hubers","Periode VJ2018")
]

 
{-Relatie 8: Een Student voert een AfstudeerOpdracht uit-}
{-Een Student doet 1 en maximaal 1 AfstudeerOpdracht. -}
{-Een AfstudeerOpdracht wordt gedaan door 1 en slechts 1 Student.-}
RELATION doetAfstudeeropdracht [Student*AfstudeerOpdracht] [UNI, TOT, INJ]
MEANING "Een Student voert een AfstudeerOpdracht uit"
PURPOSE RELATION doetAfstudeeropdracht [Student*AfstudeerOpdracht] {+De student voert gedurende zijn stageperiode een stageopdracht uit +}
POPULATION doetAfstudeeropdracht CONTAINS
[ ("Jeroen Velzeboer","Opdracht NXP Datascience");
  ("Rosanne Hubers","Opdracht OU green IT")
]

{-Relatie 9: Een AfstudeerStagecoordinator keurt een AfstudeerOpdracht-}
{-Een AfstudeerStagecoordinator keurt 1 en minimaal 1 AfstudeerOpdracht. -}
{-Een AfstudeerOpdracht wordt door 1 en slechts 1 Afstudeerstagecoördinator gekeurd.-}
RELATION keurtAfstudeeropdracht [AfstudeerStagecoordinator*AfstudeerOpdracht] [TOT, INJ]
MEANING "Een AfstudeerStagecoordinator keurt een AfstudeerOpdracht"
PURPOSE RELATION keurtAfstudeeropdracht [AfstudeerStagecoordinator*AfstudeerOpdracht] {+de afstudeerstagecoördinator keurt de afstudeeropdracht op complexiteit en HBO niveau+}
POPULATION keurtAfstudeeropdracht CONTAINS
[ ("Jose Huisman","Opdracht NXP Datascience");
  ("Jose Huisman","Opdracht OU green IT")
]

{-Relatie 10: Een AfstudeerStagecoordinator wijst een Assessor toe-}
{-Een AfstudeerStagecoordinator wijst 1 en minimaal 1 Assessor toe. -}
{-Een Assessor wordt door 1 en slechts 1 AfstudeerStagecoordinator toegewezen.-}
RELATION wijstAssessortoe [AfstudeerStagecoordinator*Assessor] [TOT, SUR, INJ]
MEANING "Een AfstudeerStagecoordinator wijst een Assessor toe"
PURPOSE RELATION wijstAssessortoe [AfstudeerStagecoordinator*Assessor] {+De afstudeerstagecoördinator benoemd de assessoren +}
POPULATION wijstAssessortoe CONTAINS
[ ("Jose Huisman","Dries Enden");
  ("Jose Huisman","Frits Vries")
]

{-Relatie 11: Een Assessor wordt gekoppeld aan een Student-}
{-Een Assessor wordt gekoppeld aan 1 en minimaal 1 Student.-}
{-Een Student wordt gekoppeld aan 1 en slechts 1 Student.-}
RELATION wordtgekoppeldaanAssessor [Assessor*Student] [TOT, INJ, SUR]
MEANING "Een Assessor wordt gekoppeld aan een Student"
PURPOSE RELATION wordtgekoppeldaanAssessor [Assessor*Student] {+Een assessor wordt gekoppeld aan student mbt afstudeerproces+}
POPULATION wordtgekoppeldaanAssessor CONTAINS
[ ("Dries Enden","Jeroen Velzeboer");
  ("Frits Vries","Rosanne Hubers")
]

{-Relatie 12: Een Online_Stagesysteem biedt AfstudeerOpdracht aan-}
{-Een Online_Stagesysteem biedt 1 en minimaal 1 AfstudeerOpdracht aan. -}
{-Een AfstudeerOpdracht wordt minimaal 1 keer aangeboden in een Online_Stagesysteem.-}
RELATION biedtAfstudeerOpdrachtStageaan [Online_Stagesysteem*AfstudeerOpdracht] [TOT, INJ]
MEANING "Een Online_Stagesysteem biedt AfstudeerOpdrachten aan"
PURPOSE RELATION biedtAfstudeerOpdrachtStageaan [Online_Stagesysteem*AfstudeerOpdracht] {+Het online stagesysteem biedt allerlei verschillende mogelijke opdrachten aan waar studenten zich op kunnen inschrijven+}
POPULATION biedtAfstudeerOpdrachtStageaan CONTAINS
[ ("Systeem SAS","Opdracht OU green IT");
  ("Systeem SAS","Opdracht NXP Datascience")
]

 
{-Relatie 13: Een DocentBegeleider begeleidt een Student-}
{-Een DocentBegeleider begeleidt 1 en minimaal 1 Student. -}
{-Een Student wordt door 1 en slechts 1 DocentBegeleider begeleid -}
RELATION dbBegeleidtStudent [DocentBegeleider*Student] [TOT, SUR, INJ]
MEANING "DocentBegeleider begeleidt een Student"
PURPOSE RELATION dbBegeleidtStudent [DocentBegeleider*Student] {+De docentbegeleider begeleidt de student gedurende zijn afstudderstageproces vanuit de school+}
POPULATION dbBegeleidtStudent CONTAINS
[ ("Jurgen Esselink","Jeroen Velzeboer");
  ("Karin Velde","Rosanne Hubers")
]
{-Relatie 14: Een BedrijfsBegeleider begeleidt een Student -} 
{-Een BedrijfsBegeleider begeleidt 1 en minimaal 1 Student. -}
{-Een Student wordt door 1 en slechts 1 BedrijfsBegeleider begeleid.-}
RELATION bbBegeleidtStudent [BedrijfsBegeleider*Student] [TOT, SUR, INJ]
MEANING "Een BedrijfsBegeleider begeleidt een Student"
PURPOSE RELATION bbBegeleidtStudent [BedrijfsBegeleider*Student]{+De bedrijfsbegeleider begeleidt de student vanuit het stagebedrijf+}
POPULATION bbBegeleidtStudent CONTAINS
[ ("Henk Jansen","Jeroen Velzeboer");
  ("Wim Kieft","Rosanne Hubers")
]

{-Relatie 15: Een BedrijfsBegeleider werkt bij het StageBedrijf-}
{-Een BedrijfsBegeleider werkt bij 1 en minimaal 1 StageBedrijf. -}
{-Een StageBedrijf heeft minimaal 1 BedrijfsBegeleider.-}
RELATION werktbij [BedrijfsBegeleider*StageBedrijf] [TOT, SUR]
MEANING "Een BedrijfsBegeleider werkt bij het StageBedrijf"
PURPOSE RELATION werktbij [BedrijfsBegeleider*StageBedrijf] {+De bedrijfsbegeleider is werkzaam bij het stagebedrijf waar de student zijn afstudeerstage uitvoert +}
POPULATION werktbij CONTAINS
[ ("Henk Jansen","NXP");
  ("Wim Kieft","OU")
]

{-Relatie 16: Een DocentBegeleider doet BedrijfsBezoek-}
{-Een DocentBegeleider doet twee en maximaal twee BedrijfsBezoeken. -}
{-Een BedrijfsBezoek wordt door 1 en slechts 1 DocentBegeleider gedaan.-}
RELATION doetBedrijfsbezoek [DocentBegeleider*BedrijfsBezoek] [TOT, SUR]
MEANING "Een DocentBegeleider doet BedrijfsBezoek"
PURPOSE RELATION doetBedrijfsbezoek [DocentBegeleider*BedrijfsBezoek]  {+Docentbegeleider doet gedurende de stage enkele keren een bedrijfsbezoek om polshoogte te nemen+}
POPULATION doetBedrijfsbezoek CONTAINS
[ ("Jurgen Esselink","1e bedrijfsbezoek");
  ("Jurgen Esselink","2e bedrijfsbezoek");
  ("Karin Velde","1e bedrijfsbezoek")
]

{-Relatie 17: Een Examenkamer verleent de Student toestemming-}
{- Een Examenkamer verleent 1 en minimaal 1 Toestemming Student. -}
{-Een Toestemming Student wordt door 1 en slechts 1 Examenkamer verleend. -}
RELATION verleentToestemmingStudent [Examenkamer*Student] [TOT, SUR, INJ]
MEANING "Een Examenkamer verleent de Student toestemming"
PURPOSE RELATION verleentToestemmingStudent [Examenkamer*Student] {+Examenkamer geeft student indien van toepassing toestemming tot afstuderen+}
POPULATION verleentToestemmingStudent CONTAINS
[ ("Examenkamer B","Jeroen Velzeboer");
  ("Examenkamer B","Rosanne Hubers")
]
 
{-Relatie 18: De Administratie archiveert Documenten-}
{-Een Administratie archiveert Documenten. -}
{-Een Document wordt door de Administratie gearchiveerd.-}
RELATION archiveertDocumenten [Administratie*Documenten] [TOT, SUR, INJ]
MEANING ": De Administratie archiveert Documenten"
PURPOSE RELATION archiveertDocumenten [Administratie*Documenten] {+Administratie houdt alle stage gerelateerde documenten bij en archiveert deze+}
POPULATION archiveertDocumenten CONTAINS
[ ("Administratie FHICT","BedrijfsBeoordeling");
  ("Administratie FHICT","APOE formulier")
]

{-Relatie 19: Een Student vult een Kritische_Zelfreflectie in-}
{-Een Student vult 1 en maximaal 1 Kritische_Zelfreflectie in. -}
{-Een Kritische_Zelfreflectie wordt door 1 en slechts 1 Student ingevuld.-}
RELATION vultKritischeZelfreflectiein [Student*Kritische_Zelfreflectie] [UNI, TOT, SUR, INJ]
MEANING "Een Student vult een Kritische_Zelfreflectie in"
PURPOSE RELATION vultKritischeZelfreflectiein [Student*Kritische_Zelfreflectie] {+Student vult zijn kritische zelfreflectie in om leerdoelen te stellen+}
POPULATION vultKritischeZelfreflectiein CONTAINS
[ ("Jeroen Velzeboer","KR Jeroen");
  ("Rosanne Hubers","KR Rosanne")
]

{-Relatie 20: Een Externe_Deskundige neemt een Assessment af-}
{-Een Externe_Deskundige neemt 1 en minimaal 1 Assessment af. -}
{-Een Assessment wordt door 1 en slechts 1 Externe_Deskundige afgenomen. -}
RELATION neemtAssessmentaf [Externe_Deskundige*Assessment] [TOT, SUR, INJ]
MEANING "Een Externe_Deskundige neemt een Assessment af"
PURPOSE RELATION neemtAssessmentaf [Externe_Deskundige*Assessment] {+Externe deskundige neemt oa het assessment af ivm objectiviteit+}
POPULATION neemtAssessmentaf CONTAINS
[ ("Peter Willems","Assessment Jeroen Velzeboer");
  ("Joyce Damstra","Assessment Rosanne Hubers")
]
{-Relatie 21: Een Examenkamer beoordeelt een Assessment -}
{-Een Examenkamer beoordeelt 1 en minimaal 1 Assessment. -}
{-Een Assessment wordt beoordeeld door 1 en slechts 1 Examenkamer. -}
RELATION beoordeeltAssessment [Examenkamer*Assessment] [TOT, SUR, INJ]
MEANING "Een Examenkamer beoordeelt een Assessment"
PURPOSE RELATION beoordeeltAssessment [Examenkamer*Assessment] {+Examenkamer beoordeeld de beoordeling vh assessment van de docenten en begeleiders+}
POPULATION beoordeeltAssessment CONTAINS
[ ("Examenkamer B","Assessment Jeroen Velzeboer");
  ("Examenkamer B","Assessment Rosanne Hubers")
]
{-Relatie 22: Een Student doet een Assessment-}
{-Een Student doet 1 en maximaal 1 Assessment. -}
{-Een Assessment wordt door 1 en slechts 1 Student gedaan.-}
RELATION doetAssessment [Student*Assessment] [UNI, TOT, SUR, INJ]
MEANING "Een Student doet een Assessment"
PURPOSE RELATION doetAssessment [Student*Assessment]{+Student gaat aan het eind vd stage op assessment +}
POPULATION doetAssessment CONTAINS
[ ("Jeroen Velzeboer","Assessment Jeroen Velzeboer");
  ("Rosanne Hubers","Assessment Rosanne Hubers")
]
{-Relatie 23: Een Mederwerker_AfstudeerBedrijf werkt bij een StageBedrijf-}
{-Een Medewerker_AfstudeerBedrijf werkt altijd bij een StageBedrijf.  -}
{-Bij een StageBedrijf werken minimaal 5 Medewerker_AfstudeerBedrijf. -}
RELATION werktbijStagebedrijf [Mederwerker_AfstudeerBedrijf*StageBedrijf] [UNI, TOT, SUR]
MEANING "Een Medewerker_AfstudeerBedrijf werkt bij een StageBedrijf"
PURPOSE RELATION werktbijStagebedrijf [Mederwerker_AfstudeerBedrijf*StageBedrijf]  {+Medewerker dient werkzaam te zijn bij het stagebedrijf om te kunnen begeleiden+}
POPULATION werktbijStagebedrijf CONTAINS
[ ("Karel Koning","NXP");
  ("Rien Hamers","OU")
]

{-Relatie 24: Een Student heeft resultaten uit het Vorig_Semester-}
{-Een Student heeft 1 en slechts 1 set aan resultaten uit Vorig_Semester. -}
{-De resultaten uit het Vorig_Semester horen bij minimaal 1 Student. -}
RELATION heeftVorigSemesterAfgerond [Student*Vorig_Semester] [UNI, INJ]
MEANING "Een Student heeft resultaten uit het Vorig_Semester"
PURPOSE RELATION heeftVorigSemesterAfgerond [Student*Vorig_Semester] {+Student moet vorig semester behaald hebben om op stage te mogen. Dit staat in de resultaten van vorig semester+}
POPULATION heeftVorigSemesterAfgerond CONTAINS
[ ("Jeroen Velzeboer","Behaald");
  ("Rosanne Hubers","Niet Behaald")
]

{-Relatie 25: Een AfstudeerOpdracht heeft Kenmerk_AfstudeerOpdracht-}
{-Een Afstudeeropdracht heeft minimaal 1 Kenmerk_AfstudeerOpdracht. -}
{-Een Kenmerk_AfstudeerOpdracht hoort bij minimaal 1 AfstudeerOpdracht. -}
RELATION heeftKenmerkAfstudeeropdracht [AfstudeerOpdracht*Kenmerk_AfstudeerOpdracht] [TOT, SUR]
MEANING "Een AfstudeerOpdracht heeft Kenmerk_AfstudeerOpdracht"
PURPOSE RELATION heeftKenmerkAfstudeeropdracht [AfstudeerOpdracht*Kenmerk_AfstudeerOpdracht] {+Afstudeeropdracht moet aan bepaalde kenmerken voldoen +}
POPULATION heeftKenmerkAfstudeeropdracht CONTAINS
[ ("Opdracht OU green IT"," Onderzoekscomponent aanwezig ");
  ("Opdracht OU green IT "," Niet bedrijfskritisch ");
  ("Opdracht OU green IT","Probleemstelling aanwezig");
  ("Opdracht NXP Datascience","Probleemstelling aanwezig")
]

{-Relatie 26: Een StageBedrijf heeft Kenmerk_StageBedrijf-}
{-Een Stagebedrijf heeft minimaal 1 Kenmerk_Stagebedrijf. -}
{-Een Kenmerk_Stagebedrijf hoort bij minimaal 1 Stagebedrijf. -}
RELATION heeftKenmerkStagebedrijf [StageBedrijf*Kenmerk_StageBedrijf] [TOT, SUR]
MEANING "Een StageBedrijf heeft Kenmerk_StageBedrijf"
PURPOSE RELATION heeftKenmerkStagebedrijf [StageBedrijf*Kenmerk_StageBedrijf]  {+Stagebedrijf moet aan bepaalde kenmerken voldoen+}
POPULATION heeftKenmerkStagebedrijf CONTAINS
[ ("NXP","Belangenverstrengeling");
  ("NXP","Te weinig fysieke aanwezigheid");
  ("OU","Uitdagende omgeving")
]
{-Relatie 27: Een BedrijfsBegeleider heeft Kenmerk_BedrijfsBegeleider-}
{-Een Bedrijfsbelegeider heeft minimaal 1 Kenmerk_Bedrijfsbegeleider.-}
{-Een Kenmerk_Bedrijfsbegeleider hoort bij minimaal 1 Bedrijfsbegeleider.-}
RELATION heeftKenmerkBedrijfsbegeleider [BedrijfsBegeleider* Kenmerk_BedrijfsBegeleider] [TOT, SUR, INJ]
MEANING "Een BedrijfsBegeleider heeft Kenmerk_BedrijfsBegeleider"
PURPOSE RELATION heeftKenmerkBedrijfsbegeleider [BedrijfsBegeleider* Kenmerk_BedrijfsBegeleider] {+Bedrijfsbegeleider moet aan bepaalde kenmerken voldoen+}
POPULATION heeftKenmerkBedrijfsbegeleider CONTAINS
[ ("Henk Jansen","HBO niveau");
  ("Wim Kieft","Onvoldoende tijd")
]
{-Relatie 28: Een AfstudeerOpdracht heeft een StageBedrijf-} 
{-Een AfstudeerOpdracht hoort bij 1 en maximaal 1 StageBedrijf -}
{-Een StageBedrijf hoort bij 1 en minimaal 1 StageOpdracht.-}
RELATION heeftStageBedrijf [AfstudeerOpdracht*StageBedrijf] [UNI, SUR, INJ]
MEANING "Een AfstudeerOpdracht heeft een StageBedrijf"
PURPOSE RELATION heeftStageBedrijf [AfstudeerOpdracht*StageBedrijf]  {+Afstudeeropdracht wordt gefaciliteerd door een StageBedrijf+}
POPULATION heeftStageBedrijf CONTAINS
[ ("Opdracht OU green IT","OU");
  ("Opdracht NXP Datascience","NXP")
]

ENDCONTEXT

**Comment by jeroenvelzeboer** [comment]
BTW: ook het script van de tutorial en een script met enkel auteurs geeft hetzelfde probleem. Ook dan krijg je enkel de 3 systeemconcepten te zien. Ik denk dat het probleem bij RAP3 ligt.

**Comment by hanjoosten** [comment]
Ik vermoed dat dit aan een van de instellingen van RAP3 ligt. Als dat zo is, dan hebben alle scripts ditzelfde probleem. Je screenshots kan ik niet openen: Ze komen allemaal uit op een page-not-found pagina.

**Comment by jeroenvelzeboer** [comment]
Als het goed is zijn ze nu wel te openen, ik heb de blokhaken verwijderd.

Ik deel het vermoeden en hoop dat het wellicht aangepast kan worden, zodat we het conceptuele model alsnog kunnen exporteren:).

**Comment by hanjoosten** [comment]
Ik heb even gekeken wat er precies aan de hand is. Het heeft te maken met de manier waarop de diagnose nu in elkaar zit. Het functioneel ontwerp document gaat er nu van uit dat de regels zijn gegroepeerd per thema. Dat kan je doen door regels, relaties die in eenzelfde thema horen te bundelen door middel van het [PATTERN statement](https://ampersandtarski.gitbooks.io/documentation/syntax/pattern.html). Je zult zien dat als je dat doet, dat je met de generator van het functioneel design document betere resultaten behaalt. 

Er wordt momenteel gewerkt aan een vernieuwde opzet van het functioneel design document, want er zitten nogal wat onhebbelijkheden in. Helaas komt dat te laat voor jullie. Hopelijk kan je met dit antwoord uit de voeten. Zo niet, heropen dit issue dan gerust. @EstherHageraats , wellicht goed om dit ergens in de documentatie voor de studenten te vermelden?
