### ISSUE TITLE
Ontbreken conceptuele modellen van patterns door bug in template functioneel ontwerp

### ISSUE THREAD

**Issue by alicepranger** [AmpersandTarski/RAP#50]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
Rap 3

#### Wat ik verwachtte
Ik verwachtte een functionele specificatie met daarin per pattern 2 conceptuele modellen, een met de relaties binnen het pattern en een met de rules binnen het pattern.

#### Wat er gebeurde
Tijdens het maken van ons adviesverslag lopen we tegen een issue aan.

We wilden graag toelichten welke patterns we onderkennen binnen ons proces en deze voorzien van de bijbehorende modellen. Per pattern (wij hebben er vijf) is er een model dat alle relaties weergeeft binnen een pattern en een model dat alle rules weergeeft binnen een pattern. Deze kan je uit de functionele specificatie halen die gegenereerd wordt door RAP 3.

Echter lijkt het alsof er een bug zit in de template van deze functionele specificatie in RAP3. Sinds de start van dit project lijkt het alsof hij een aantal concepten uit de template vast houdt die helemaal niet voorkomen in ons script.

Dit is het zelfde als je een voorbeeldscript gebruikt, bijvoorbeeld "enrollment" uit de RAP3 tutorial. Daardoor weten we zeker dat het niet aan ons script ligt.

Zie screenshots hieronder, wij onderkennen geen concepten zoals DateTime, Session en Role. En het voorbeeldscript "enrollment" onderkent dit ook niet. Toch wordt dit in beide gevallen wel in de functionele specificatie opgenomen.

Nou zou dit op zich geen probleem zijn als het een soort van extra was geweest (wat wij eerst dachten dat het een voorbeeld was), echter valt door deze bug 2 van de modellen weg die wij wel nodig hebben. Van 1 van onze patterns ontbreekt het model met de relaties binnen het pattern. En voor een andere pattern ontbreekt het model met de rules binnen dat pattern.

In de bijlage het functionele ontwerp van ons script (de bug is te zien op de pagina`s: 15 en 28). Ook in het logisch gegevensmodel komen deze random concepten voor die niet uit ons script komen (zie pagina 53). Ook zie je dit terug in de verschillende tabellen en diverse opsommingen in het verslag.

Omdat het dus niet uitmaakt welk script je erin zet (ons eigen of het voorbeeldscript) verwachten wij dat meer studenten deze bug hebben.

#### Stappen om dit te reproduceren
1.  Compileer een script met daarin diverse patterns met relaties en rules
2. Download de functionele specificatie
3. Zoek per pattern naar 2 modellen, 1 met relaties binnen pattern, 1 met rules binnen pattern
4. Je ziet dat voor beiden soorten modellen er voor een pattern een ontbreekt en wordt vervangen door een conceptueel model met concepten die helemaal niet voorkomen in het script. 

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/36029913/35669734-61d8cb00-0736-11e8-818c-58b1f28d139a.png)
[Functionele specificatie2018-01-31T150948.pdf](https://github.com/AmpersandTarski/RAP/files/1684790/Functionele.specificatie2018-01-31T150948.pdf)

**Comment by hanjoosten** [comment]
Zou je je .adl script hier ook willen uploaden? dan kan ik een diagnose stellen.

**Comment by hanjoosten** [comment]
Het pattern 'SystemSpecific' bevat een paar concepten die nuttig/nodig zijn om een prototype goed te laten functioneren. Het is echter niet zo dat dat pattern een ander kan vervangen. Die wordt echt toegevoegd. 

Ik denk nu aan de volgende mogelijkheden:

- Heb je een Pattern met dezelfde naam als de Context?
- Heb je je PATTERN / ENDPATTERN keywords staan zoals je ze verwacht?

**Comment by alicepranger** [comment]
Beste Han,

Bedankt voor je snelle reactie, hierbij ook het script. 
Ik kan hem alleen als txt uploaden, bestandtype ADL is niet toegestaan als bijlage.
[Rules0.78.txt](https://github.com/AmpersandTarski/RAP/files/1684965/Rules0.78.txt)

Ah oke nee dat dachten wij ook al dat het een voorbeeld was, maar wij missen dus de volgende twee modellen:
- Het conceptuele model met de regels van pattern "WijzigingsformulierVerwerken"
- Het conceptuele model met de relaties van pattern "TekenplaatjeInvoerEnControle"

Als antwoord op je vragen:
- Er is geen PATTERN met dezelfde naam als de CONTEXT
- Volgens mij worden alle patterns gestart met PATTERN en gesloten met ENDPATTERN

**Comment by hanjoosten** [comment]
Ik weet niet wat er precies aan de hand is. Het kan van alles zijn, maar ik kan het zelf niet reproduceren. Ik heb met de command line tool van Ampersand bijgaand resultaat behaald. 
[Rules0_78.pdf](https://github.com/AmpersandTarski/RAP/files/1687299/Rules0_78.pdf)

@LloydRutledge Is het mogelijk dat de site tegen grenzen van resources aan loopt? Wordt er gemonitord op gebruik van geheugen / harde schijf?

@alicepranger Helaas kan ik verder op dit moment niet veel voor je betekenen.

**Comment by RieksJ** [comment]
Ik herken figuur 4.1 als een onderdeel van de SIAM module. Deze module wordt door RAP gebruikt. In het script van Alice wordt daar niet naar verwezen. @hanjoosten: Helpt dit bij de diagnose? 

@alicepranger toen ik even door je script ging zag ik erg veel bijectieve relaties (i.e. relaties met de vier eigenschappen UNI,TOT,INJ,SUR). In mijn ervaring komen bijectieve relaties vrijwel nooit voor (< 0,01%). 
Een voorbeeld. 
~~~
RELATION wordtGevoerdDoor [Plangesprek*Teamleider] [UNI,TOT,INJ,SUR]
MEANING "Het plangesprek wordt gevoerd door een teamleider."
~~~
Omdat dit een bijectie is betekent het niet alleen dat elk plangesprek wordt door slechts 1 teamleider gevoerd (dat zou immers goed kunnen), maar ook dat elk teamleider precies 1 plangesprek heeft gevoerd - niet meer en ook niet minder. En dat gaat ook nooit veranderen. Dat lijkt me stug.

**Comment by alicepranger** [comment]
@hanjoosten , bedankt voor je moeite! 

Maar het is je wel gelukt om het te reproduceren. Ook in het functionele ontwerp dat jij hebt geupload missen twee conceptuele modellen. Er zijn maar 4 modellen voor regels binnen een pattern en 4 modellen voor relaties binnen een pattern. Terwijl wij 5 patterns hebben. Het zijn ook 2 patterns die een model missen, bij de ene mist het relatiemodel en bij een ander mist het regelmodel. 

@LloydRutledge Hopelijk ligt het inderdaad aan de resources, want het zou wel erg jammer zijn als we niet alle modellen in het verslag kunnen opnemen. 

Wat @RieksJ zegt klopt inderdaad. Wij hebben in ons script geen verwijzigingen naar deze SIAM module en toch komen er 2 modellen van de SIAM terug als model in plaats van de modellen van de patterns die we wel willen. 

Bedankt voor de tip over de bijectie. We gaan dit aanpassen en nog eens goed doorlopen, want we waren er inderdaad al tegen aan gelopen dat we dan wat overtredingen hebben. Die zijn er nu uit. Onder andere door het aanpassen van de diverse multipliciteiten (minder bijecties).

Allebei vriendelijk bedankt voor de genome moeite om ons te helpen. 

Groet,
Mike, Larissa en Alice

**Comment by hanjoosten** [comment]
Dag Alice,

In de door mij geuploade pdf staat figuur 4.13 de door jouw als afwezig gemeldde model van de regels van `WijzigingsformulierVerwerken`. 

Er is inderdaad geen plaatje van (nieuwe) relaties in `TakenplaatjeInvoerEnControle`. Dat komt door de huidige opzet van het document. Per thema (=pattern) worden alleen de nog niet in een eerder thema besproken concepten en relaties afgedrukt. Hierdoor wordt veel dubbeling voorkomen. het thema `TakenplaatjeInvoerEnControle` introduceert geen nieuwe relaties. Dat is (naar alle waarschijnlijkheid) de reden dat er geen plaatje van wordt afgedrukt.

**Comment by hanjoosten** [comment]
@RieksJ : Het pattern 'Systemspecific' is een ingebouwd pattern, nodig voor het prototype vanaf de refactorslag van @Michiel-s . Dat wordt altijd meegegenereerd en bestaat daardoor ook in het gegnereerde functional design document.

**Comment by alicepranger** [comment]
@hanjoosten dankjewel voor de toelichting. We hebben ervoor gekozen het vijfde pattern te verdelen over twee andere patterns. Nu krijgen we wel alle modellen. Bedankt voor de hulp.

**Comment by hanjoosten** [comment]
Graag gedaan
