### ISSUE TITLE
Interface is niet te maken bij meer dan 14 relaties

### ISSUE THREAD

**Issue by MichaelRBakker** [AmpersandTarski/RAP#51]
[script.txt](https://github.com/AmpersandTarski/RAP/files/1686993/script.txt)

#### Versie van Ampersand (in de CLI:  >  ampersand --version)

[script.txt](https://github.com/AmpersandTarski/RAP/files/1686991/script.txt)

#### Wat ik verwachtte
Ik verwacht dat na te drukken op de knop prototype ik een link krijg naar het prototype en dus een interface kan gaan gebruiken.

#### Wat er gebeurde
Met 13 relaties lukt het wel, voeg ik nummer 14 toe dan gaat het fout.

#### Stappen om dit te reproduceren
1. Probeer bijgevoegd script te complileren en maak een protoype aan.
2. Dat lukt niet.
3. Haal de relatie heeftDocentinzetStatus weg (streepjes ervoor)
4. Compileer het script en maak een prototype aan.
5. Dat lukt nu wel.

**Comment by hanjoosten** [comment]
Er zijn met dit script een aantal dingen aan de hand:

1. Je hebt dit waarschijnlijk al enige tijd geleden gedaan, waardoor je last hebt van een inmiddels verholpen issue #29. Het nummer op regel 175 dien je te vervangen:
`INTERFACE Overview : "_SESSION"[SESSION]`

2. De relatie `heeftDocentinzetStatus` heeft twee eigenschappen. (TOT en SUR). De populatie voldoet hier niet aan, zodat er geen prototype kan worden gegenereerd. Bij het compileren krijg je een foutmelding die dat vermeldt.

**Comment by MichaelRBakker** [comment]
Dank voor het antwoord, dat lost het probleem inderdaad op. Mijn vraag is alleen nog, waar zie ik de foutmelding die bij het compileren wordt vermeld?

**Comment by hanjoosten** [comment]
Sorry voor de late reactie. Als je je script compileert, dan staat er een melding direct onder. Op de plek waar je "Finished processing your model." ziet staan bij een goed situatie. Probeer het maar eens uit, door een script die niet goed is te compileren. Dan zie je het wel.
