### ISSUE TITLE
Population invisible in Enroll prototype

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#53]
Dit issue is een fout, die voorkomt in de versie van RAP die draaide direct na de crash van issue #52. Onduidelijk is nog welke consequenties deze fout voor studenten heeft. Daarom is het een normal prio bug.

#### Wat ik verwachtte
Ik verwachtte dat ik het Enroll script zou kunnen executeren en dat ik dat populatie te zien zou krijgen. 

#### Wat er gebeurde
Ik kreeg geen populatie te zien

#### Stappen om dit te reproduceren
1. Ik compileerde ``Enroll.adl``
2. Ik draaide het gegenereerde prototype
3. Ik herstartte de database

#### Screenshot / Video
![afbeelding](https://user-images.githubusercontent.com/275768/35943506-973b9e80-0c59-11e8-9d40-a2bc72b3ea33.png)

#### Context / Source van ampersand script
```
CONTEXT Enrollment IN DUTCH
PURPOSE CONTEXT Enrollment
{+ A complete course consists of several modules.
Students of a course can enroll for any module that is part of the course.
+}

PATTERN Courses
-- The concepts
CONCEPT Student "Someone who wants to study at this institute"
CONCEPT Course "A complete course that prepares for a diploma"
CONCEPT Module "An educational entity with a single exam"

-- The relations and the initial population
RELATION takes [Student*Course]
MEANING "A student takes a complete course"

POPULATION takes CONTAINS
   [ ("Peter", "Management")
   ; ("Susan", "Business IT")
   ; ("John", "Business IT")
   ]

RELATION isPartOf [Module*Course]
MEANING "A module part of a complete course"

POPULATION isPartOf CONTAINS
   [ ("Finance", "Management")
   ; ("Business Rules", "Business IT")
   ; ("Business Analytics", "Business IT")
   ; ("IT-Governance", "Business IT")
   ; ("IT-Governance", "Management")
   ]

RELATION isEnrolledFor [Student*Module]
MEANING "Students enroll for each module in the course separately"

-- The one rule in this model
RULE ModuleEnrollment: isEnrolledFor |- takes;isPartOf~
MEANING "A student can enroll for any module that is part of the course the student takes"
MESSAGE "Attempt to enroll student(s) for a module that is not part of the student's course."
VIOLATION (TXT "Student ", SRC I, TXT " enrolled for the module ", TGT I, TXT " which is not part of the course ", SRC I[Student];takes)
ENDPATTERN

INTERFACE Overview : "0d61d44c9c5a4c353bf7ab769ab8ea0c"                 cRud
TABS [ Students     : V[SESSION*Student]        cRuD
       COLS [ "Student" : I[Student]            cRud
            , "Enrolled for" : isEnrolledFor    cRUD
            , "Course" : takes                  CRUD 
            ]
     , Course     : V[SESSION*Course]           cRuD
       COLS [ "Course" : I                      cRud
            , "Modules" : isPartOf~             CRUD
            ]
     , Modules : V[SESSION*Module]              cRuD
       COLS [ "Modules" : I                     cRud
            , "Course" : isPartOf               cRud
            , "Students" : isEnrolledFor~       CRUD
            ]
     ]

ENDCONTEXT
```

**Comment by LloydRutledge** [comment]
Ik heb deze op de cursussite gepost:

Subject: Met population problemen gebruik even weer http://ampersand.tarski.nl/RAP3

rap.cs.ou.nl/RAP3 heeft vanavond een probleem waardoor script populations eventueel niet herkent worden in de prototypes. Als je dit probleem hebt dan gebruik even weer de backup server http://ampersand.tarski.nl/RAP3 . We proberen in de tussentijd het probleem op de hoofdserver om op te lossen. Ik post hier een mededeling als de hoofdserver weer helemaal goed draait.

Dit weekend is de grote einddatum en dus zullen de studenten flink bezig vanavond zijn. Ze hebben dus een goede server nodig.

Hoor ik het graag als ik iets kan doen.

-Lloyd

**Comment by Michiel-s** [comment]
Known issue: #41 
And must be fixed/preventief, issue already exists: AmpersandTarski/Ampersand#635

**Comment by stefjoosten** [comment]
At first glance, I got the deadlock error. This is indeed the same as AmpersandTarski/Ampersand#635. We'll just wait for that fix.

However, closer inspection shows that this bug is about population not shown. That is why I changed the title of this issue. This one needs a closer look.

**Comment by stefjoosten** [comment]
# Analysis
I have restarted the docker containers, but that makes no difference at all. Restarting containers implies restarting the database as well, so that too can be excluded as a cause.

**Comment by stefjoosten** [comment]
@LloydRutledge can you verify experimentally whether the analysis above explains your error ?

Here is what you do to verify (on the current machine).
1. First reproduce the bug.
2. Then establish that The ``INTERFACE Overview`` in your script contains a long number where it should say ``_SESSION``.
3. Replace the number by ``_SESSION`` and check whether it works.
4. Report the result.

**Comment by LloydRutledge** [comment]
Yes, I repeated these steps. Is started (still) broken at 1. At 4 the population was back.
