### ISSUE TITLE
Violation message is niet duidelijk zichtbaar

### ISSUE THREAD

**Issue by MichaelRBakker** [AmpersandTarski/RAP#54]
[ONDERWIJS_108.txt](https://github.com/AmpersandTarski/RAP/files/1709036/ONDERWIJS_108.txt)
[delivery case met violation.txt](https://github.com/AmpersandTarski/RAP/files/1709037/delivery.case.met.violation.txt)

[Case Onderwijs.pdf](https://github.com/AmpersandTarski/RAP/files/1709024/Case.Onderwijs.pdf)

#### Versie van Ampersand (in de CLI:  >  ampersand --version)
RAP3 omgeving

#### Wat ik verwachtte
Ik verwacht dat ik na het aanmaken van een VIOLATION die ook terug zie in de specificaties. Uiteraard na het overtreden daarvan door het aanpassen van de populatie.
Ik gebruik 2 cases om vast te stellen hoe zo'n VIOLATION terug komt.
1. Case Delivery met een aangepaste populatie (stond al in de case)
2. Case van onszelf

Bij case 1. Delivery verwacht ik en zie ik dat de proces regel wordt overtreden. Dat gebeurt ook netjes, ik zie ook terug: De populatie in dit script overtreedt 0 invarianten en 1 procesregel
• Regel allAccepted Totaal aantal taken: 1.
Wat ik hier niet zie is dat wat je in de VIOLATION zelf opneemt als bericht, o.a. het stuk tekst "has not accepted the order". Dit stuk tekst zie ik nergens terug. En dat vind ik vreemd.

Bij case 2. van onszelf, verwacht ik dat ik een proces regel overtreed. Ik heb de VIOLATION zoveel mogelijk "nagemaakt" op basis van de status die wij gebruiken. De regel overtreed ik wel. Maar de tekst is De populatie in dit script overtreedt 2 invarianten en 0 procesregels.
• Regel allGeaccordeerd. Dus geen overtreding van een procesregel.
 
#### Wat er gebeurde
Zie hierboven. 

#### Stappen om dit te reproduceren
DELIVERY CASE
1. De adl file is bijgevoegd, ook de functionele specificatie. voor de delivery case gaat het om de rule allAccepted.
2. De relatie orderAccepted hiervan de populatie even afgesterd.
3. De relatie orderReceived hiervan de populatie actief gemaakt
4. De rule wordt hiermee overtreden.
5. Zoek op tekst "has not accepted the order", die is nergens te vinden.

ONZE EIGEN CASE ONDERWIJS
1. De adl files is bijgevoegd. Evenals de functionele specificatie.
2. De relatie heeftWijzigingStatus hiervan in de populatie de regel ("Wijziging_IV" , "Aangevraagd") even uitgesterd.
3. De rule wordt hiermee overtreden.
4. Zoek op procesregel overtreden. Dat gebeurt niet. Zoek op de tekst in de VIOLATION. Ook niet te vinden. 
Zie blz 16, in specificatie "CASE ONDERWIJS" : regel • Regel allGeaccordeerd wordt overtreden.

#### Screenshot / Video
[Case Delivery.pdf](https://github.com/AmpersandTarski/RAP/files/1709023/Case.Delivery.pdf)

**Comment by MichaelRBakker** [comment]
Ten overvloede mogelijk, het gaat om de regel allGeaccordeerd waarbij een VIOLATION is opgenomen.

**Comment by hanjoosten** [comment]
Dag Michael,
Ik heb even snel gekeken. Helaas is een van de twee bestanden die je hebt geupload niet te lezen. Die heb je waarschijnlijk als word document (rtf) opgeslagen, niet als tekst. 
Wellicht helpen de volgende opmerkingen je toch wat verder:

- Om aan te geven dat een regel een procesregel is, en geen invariant, moet bekend worden gemaakt welke rol verantwoordelijk is om overtredingen van die regel op te heffen (dus wie heeft er werk te doen, als een procesregel wordt overtreden). Zoiets wordt aangegeven door een statement in de vorm van `ROLE <rolnaam> MAINTAINS <naam van de regel>`. Zo'n statement zie ik niet terug in je bestand. Daardoor heb je een invariant, en géén procesregel.

- een snelle blik op je regel doet me vermoeden dat je wat anders opschrijft dan wat wellicht je intentie is. Realiseer je hierbij dat `heeftWijzigingStatus;"W_Geaccordeerd";heeftWijzigingStatus~` over het algemeen ook tweetallen kan opleveren, die niet in `I` zitten. Meestal zie je hier het pattroon `I /\(heeftWijzigingStatus;"W_Geaccordeerd";heeftWijzigingStatus~)`

**Comment by MichaelRBakker** [comment]
Beste Han,
Dank voor jouw reactie. Dat hielp! Ik overtreedt nu de procesregel en ook precies wat ik verwacht. Wat ik nog wel mis is de verwerking van de regel VIOLATION. Ik zie eigenlijk nergens terug waar de resultaten zichtbaar zijn. Sterker nog met of zonder VIOLATION geeft bij mij hetzelfde resultaat. Bijgaand ook een nieuwe bijlage waarin de VIOLATION RULE is opgenomen.
[Onderwijs_case.txt](https://github.com/AmpersandTarski/RAP/files/1712040/Onderwijs_case.txt)

**Comment by MichaelRBakker** [comment]
Zie net dat het terugkomt in de interface. En niet in de specificaties. Issue kan wat mij betreft worden gesloten.
![image](https://user-images.githubusercontent.com/36052129/36045687-d5843246-0dd6-11e8-9763-eb023145aeee.png)
