### ISSUE TITLE
ACE editor field does not appear

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#56]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
Ampersand-v3.9.4 [feature/refactor_ifc:0a719dad3], build time: 28-Apr-18 23:57:35 West-Europa (zomertijd)

#### Wat ik verwachtte
Ik verwachtte dat ik een ace editor tot mijn beschikking zou hebben voor het maken van een script.

#### Wat er gebeurde
Nadat ik was ingelogd en een nieuw script wilde maken, zag ik niet het ACE veld. (Zie screenshot van wat ik wél zag. 

#### Stappen om dit te reproduceren
1. Inloggen als stefj 
2. Alle rollen 'aanzetten' 
3. Op plusje klikken om een nieuw script te maken
4.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1159672/39401283-9fc731e6-4b41-11e8-9ec7-47575c7289db.png)

**Comment by Michiel-s** [comment]
Did you run ‘gulp build-ampersand’ and ‘gulp build-project’ after generating the prototype? Rieks explained howto in the doc about migrating to refactored prototype backend.

**Comment by stefjoosten** [comment]
The Dockerfile for RAP3 contains run ‘gulp build-ampersand’ and ‘gulp build-project’. So this issue cannot occur in RAP3.
