### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#57]
Hieronder de door mij gebruikte versie en het commando om RAP te vertalen:
![afbeelding](https://user-images.githubusercontent.com/275768/39403895-e335e522-4b86-11e8-9826-e7933d1be6f8.png)
Ik heb een verse XAMPP neergezet, met PHP en MariaDB en Apache helemaal fris.
![afbeelding](https://user-images.githubusercontent.com/275768/39403922-434b3d0e-4b87-11e8-9f32-3322560fcae9.png)
Ik verwachtte dat RAP3 zou draaien, maar ik kreeg een cannot connect to database. Ondanks dat ik het account ampersand op de database heb gemaakt...
![afbeelding](https://user-images.githubusercontent.com/275768/39403929-7f7a9d1a-4b87-11e8-96ec-083aa83bcdbf.png)

Wellicht heeft @hanjoosten of @Michiel-s een idee wat ik nu weer fout doe?

**Comment by Michiel-s** [comment]
Ik heb een vermoeden, omdat ik zelf ook tegen een issue aanliep toen ik vorige week de xampp stack opnieuw installeerde. Bij mij waren een aantal php modules/extenties niet meer aan bij default. Eentje daarvan is de ‘mysqli’ extensie. Zou je in je php.ini (XAMPP/php folder) eens willen kijken of deze mysqli extensie is opgenomen.

**Comment by stefjoosten** [comment]
Ik heb hem aangezet in `C:\Program Files\PHP\php.ini`, en vervolgens de Apache server uit en aan gezet in de XAMPP console. Het effect was 0,nop...

**Comment by stefjoosten** [comment]
Dit issue is opgelost in AmpersandTarski/Ampersand#775.
