### ISSUE TITLE
Als student wil ik tekst kunnen intypen in het "insert new script" scherm, om mijn scripts te kunnen vertalen en verwerken in RAP.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#58]
Ik ben RAP3 aan het uitproberen in de nieuwe user interface. 
Om dit te kunnen reproduceren geef ik hieronder de inhoud van de gegenereerde `...\htdocs\RAP3\generics\settings.json`:
~~~
{
    "mysqlSettings": {
        "dbUser": "ampersand",
        "dbHost": "localhost",
        "dbPass": "ampersand",
        "dbsignalTableName": "__all_signals__",
        "dbName": "ampersand_rap3dev"
    },
    "environment": "EnvironmentOptions {envArgs = [\"RAP3dev.adl\",\"-pD:\\\\htdocs\\\\RAP3\"], envArgsCommandLine = [\"RAP3dev.adl\",\"-pD:\\\\htdocs\\\\RAP3\"], envArgsFromConfigFile = [\"--verbose\",\"--customizations=customizations;customizations-dev\",\"--meta-tables\",\"--add-semantic-metamodel\"], envProgName = \"ampersand\", envExePath = \"C:\\\\Users\\\\sjo\\\\AppData\\\\Roaming\\\\local\\\\bin\\\\ampersand.exe\", envLocalTime = 2018-04-30 14:54:14.6924032, envDirOutput = Just \"D:\\\\AmpersandJunkFiles\\\\\", envDirPrototype = Nothing, envDbName = Nothing, envPreVersion = Nothing, envPostVersion = Nothing}",
    "versionInfo": "Ampersand-v3.9.4 [feature/refactor_ifc:0255495], build time: 28-Apr-18 08:23:39 West-Europa (zomertijd)",
    "contextName": "RAP3"
}
~~~

Dit issue is gerelateerd aan de branch `feature/refactor_ifc` van de ampersand compiler.

Ik heb `RAP\RAP3\RAP3dev.adl` vertaald met Ampersand-v3.9.4 [feature/refactor_ifc:0255495]. Ik verwachtte dat ik een script zou kunnen aanbieden ter vertaling. Ik kreeg echter een dood scherm, waarin ik niets kan aanbieden.. Ik gebruik een YAML-file om alle opties reproduceerbaar te houden. Reproduceren kan vanuit AmpersandTarski/RAP@2d9c5aa391d5b206a80742ec4b17bb353c1a7071, en dan:
1. wijzig de directory (CD) naar `...\git\RAP3\\
2. geef commando: `ampersand RAP3dev.adl -pD:\htdocs\RAP3`
3. open de applicatie vanaf `http://localhost/RAP3`
4. login met je eigen credentials of registreer
5. Klik op het "+"-symbol (plus-symbool) rechts bovenin en probeer je eigen script in te voeren.

Dit is wat ik zag:
![afbeelding](https://user-images.githubusercontent.com/275768/39429156-4919d764-4c8a-11e8-9332-dcfd2e646505.png)

**Comment by hanjoosten** [comment]
This is the same as issue #56
