### ISSUE TITLE
Save the content without Save button, whenever the focus changes.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#6]
## Problem

When I do some typing in the ACE area, and I leave it without first hitting the Save button, the typeing will vanish whenever the screen is refreshed. Refreshing can be done because the user changes the focus to some other field and modifies the value of that field. 
## Diagnosis

Normally, the Zwolle interface saves the content of any field when the focus of the control changes. We should do that too with the ACE field. The Save button should be omitted.

**Comment by hanjoosten** [comment]
@Michiel-s , I just did some fiddling around with the HTML template, It seems to me, that data-ng-blur should do the trick, but I cannot get data-ng-blur to trigger.

**Comment by stefjoosten** [comment]
fixed.
