### ISSUE TITLE
Rule violation disguised as php-error?

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#62]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
RAP3 december 2018

#### Wat ik verwachtte
I expect a violation of a multiplicity constraint to look like any other violation: red text within the protype.

#### Wat er gebeurde
The script compiles, a prototype can be generated.
After clicking on "launch prototype" the following message comes up:
"Warning: require_once(/var/www/html/RAP3/scripts/esthermaria/generated/Script_1544192169_00595427/prototype/src/../lib/autoload.php): failed to open stream: No such file or directory in /var/www/html/RAP3/scripts/esthermaria/generated/Script_1544192169_00595427/prototype/src/bootstrap.php on line 26

Fatal error: require_once(): Failed opening required '/var/www/html/RAP3/scripts/esthermaria/generated/Script_1544192169_00595427/prototype/src/../lib/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/RAP3/scripts/esthermaria/generated/Script_1544192169_00595427/prototype/src/bootstrap.php on line 26"

Students said that this was the result of their population not meeting a multiplicity constraint. (see screenshot from their message on the discussion forum of the OU"
![schermafdruk 2018-12-10 16 35 33](https://user-images.githubusercontent.com/18698059/49742863-be6fe480-fc99-11e8-8dac-401e249233a1.png)

Also attached is their code
[IT_customer12.txt](https://github.com/AmpersandTarski/RAP/files/2663747/IT_customer12.txt)

#### Stappen om dit te reproduceren
I reproduced the issue succesfully in RAP3:
1. upload the code
2. compile
3. create prototyp
4. launch prototype
I'll try to get rid of the error by changing the code, but first let's save this....

**Comment by EstherHageraats** [comment]
I cannot get rid of the php-error. even deleting all [inj, sur] will not do the trick. I have asked the students to mail me the code where they say they solved the issue. 
In the meantime, if anyone has any ideas/comments, let me know.

**Comment by EstherHageraats** [comment]
Shoot....I cannot reproduce any of it anymore. So at this moment there is nothing to do here.
I'll close this one untill it comes up again.

**Comment by EstherHageraats** [comment]
.I cannot reproduce any of it anymore. So at this moment there is nothing to do here.
I'll close this one untill it comes up again.

**Comment by hanjoosten** [comment]
This could be anything. I try to reproduce this on my local machine. The first thing I did is to compile the script. This immediately gives a compile error. This could be the root problem. 

Some quick observations:

- I use a more recent (development) version of ampersand. I do not think however that the error in the scipt is new. I am pretty convinced that the version of the ampersand generator currently used within RAP3 will catch that same error:

```
Violations of rule "INJ projectLeader[Projectcode*Employeecode]":
- [("E1","E1"), ("E3","E3")]

Violations of rule "INJ projectMember[Projectcode*Employeecode]":
- [("E2","E2")]

Violations of rule "INJ requiredModules[Projectcode*Module]":
- [("Module3","Module3"), ("Module4","Module4"), ("NVT","NVT")]

Violations of rule "SUR packageModule[Customer*Module]":
- [("Module1","Module1"), ("Module2","Module2"), ("Module3","Module3"), ("Module4","Module4"), ("NVT","NVT")]

Violations of rule "SUR projectLeader[Projectcode*Employeecode]":
- [("E4","E4"), ("E5","E5"), ("E6","E6")]

Violations of rule "SUR projectMember[Projectcode*Employeecode]":
- [("E3","E3")]

Violations of rule "SUR requiredProducts[Projectcode*Product]":
- [("Module1","Module1"), ("Module2","Module2"), ("Module3","Module3"), ("Module4","Module4"), ("Product1","Product1"), ("Product2","Product2"), ("Product3","Product3"), ("Product4","Product4")]

Violations of rule "UNI budgetProject[Projectcode*Budgethour]":
- [("P1","P1")]

Violations of rule "UNI employeeName[Employeecode*Employeename]":
- [("E1","E1"), ("E2","E2"), ("E3","E3"), ("E4","E4"), ("E5","E5"), ("E6","E6")]

Violations of rule "UNI projectName[Projectcode*Projectname]":
- [("P1","P1"), ("P2","P2"), ("P3","P3"), ("P4","P4"), ("P5","P5"), ("P6","P6")]

Violations of rule "UNI projectStatus[Projectcode*ProjectStatus]":
- [("P1","P1")]

Signals for initial population:
Rule(s): ["INJ projectLeader[Projectcode*Employeecode]"]
  Conjunct   :  -projectLeader [Projectcode*Employeecode]~; -I[Projectcode];projectLeader [Projectcode*Employeecode]\/ -I[Employeecode]
  Violations : [("E1","E1"), ("E3","E3")]
Rule(s): ["INJ projectMember[Projectcode*Employeecode]"]
  Conjunct   :  -projectMember [Projectcode*Employeecode]~; -I[Projectcode];projectMember [Projectcode*Employeecode]\/ -I[Employeecode]
  Violations : [("E2","E2")]
Rule(s): ["INJ requiredModules[Projectcode*Module]"]
  Conjunct   :  -requiredModules [Projectcode*Module]~; -I[Projectcode];requiredModules [Projectcode*Module]\/ -I[Module]
  Violations : [("Module3","Module3"), ("Module4","Module4"), ("NVT","NVT")]
Rule(s): ["UNI budgetProject[Projectcode*Budgethour]"]
  Conjunct   :  -budgetProject [Projectcode*Budgethour]; -I[Budgethour];budgetProject [Projectcode*Budgethour]~\/ -I[Projectcode]
  Violations : [("P1","P1")]
Rule(s): ["UNI employeeName[Employeecode*Employeename]"]
  Conjunct   :  -employeeName [Employeecode*Employeename]; -I[Employeename];employeeName [Employeecode*Employeename]~\/ -I[Employeecode]
  Violations : [("E1","E1"), ("E2","E2"), ("E3","E3"), ("E4","E4"), ("E5","E5"), ("E6","E6")]
Rule(s): ["UNI projectName[Projectcode*Projectname]"]
  Conjunct   :  -projectName [Projectcode*Projectname]; -I[Projectname];projectName [Projectcode*Projectname]~\/ -I[Projectcode]
  Violations : [("P1","P1"), ("P2","P2"), ("P3","P3"), ("P4","P4"), ("P5","P5"), ("P6","P6")]
Rule(s): ["UNI projectStatus[Projectcode*ProjectStatus]"]
  Conjunct   :  -projectStatus [Projectcode*ProjectStatus]; -I[ProjectStatus];projectStatus [Projectcode*ProjectStatus]~\/ -I[Projectcode]
  Violations : [("P1","P1")]
Rule(s): ["SUR requiredProducts[Projectcode*Product]"]
  Conjunct   :  -I[Product]\/requiredProducts [Projectcode*Product]~;requiredProducts [Projectcode*Product]
  Violations : [("Module1","Module1"), ("Module2","Module2"), ("Module3","Module3"), ("Module4","Module4"), ("Product1","Product1"), ("Product2","Product2"), ("Product3","Product3"), ("Product4","Product4")]
Rule(s): ["SUR packageModule[Customer*Module]"]
  Conjunct   :  -I[Module]\/packageModule [Customer*Module]~;packageModule [Customer*Module]
  Violations : [("Module1","Module1"), ("Module2","Module2"), ("Module3","Module3"), ("Module4","Module4"), ("NVT","NVT")]
Rule(s): ["SUR projectLeader[Projectcode*Employeecode]"]
  Conjunct   :  -I[Employeecode]\/projectLeader [Projectcode*Employeecode]~;projectLeader [Projectcode*Employeecode]
  Violations : [("E4","E4"), ("E5","E5"), ("E6","E6")]
Rule(s): ["SUR projectMember[Projectcode*Employeecode]"]
  Conjunct   :  -I[Employeecode]\/projectMember [Projectcode*Employeecode]~;projectMember [Projectcode*Employeecode]
  Violations : [("E3","E3")]
ERROR: No prototype generated because of rule violations.
```

- If there are errors in the script, no prototype will be generated. That could explain why such a file cannot be found. But that's a wild guess.
- Since the version that is currently in use in production, a refactoring of the frontend has been done. there have been improvements on these kind of errors. @Michiel-s might be able to tell if these kind of errors should be history by now.
