### ISSUE TITLE
Link naar RAP3 klopt niet in documentatie

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [AmpersandTarski/RAP#63]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
http://rap.cs.ou.nl/RAP3
http://ampersand.tarski.nl/RAP3/#/Login

#### Wat ik verwachtte
De link in de documentatie verwijst naar http://rap.cs.ou.nl/RAP3. Ik verwachte dat ik mij kon registeren

#### Wat er gebeurde
Ik vulde mijn naam in, plus email, plus wachtwoord (2x), maar zonder studentnummer. Vervolgens gaat het systeem plat, en is via geen enkele browser of computer meer te bereiken.

Zo te zien is de link in de documentatie fout. De link http://ampersand.tarski.nl/RAP3/#/Login werkt zonder problemen.

#### Stappen om dit te reproduceren
1. Zie boven
2.
3.
4.

#### Screenshot / Video
![login error 1](https://user-images.githubusercontent.com/46109652/50403573-eb46f000-079f-11e9-9a95-850ca052d2b2.jpg)
![login error 2](https://user-images.githubusercontent.com/46109652/50403574-ebdf8680-079f-11e9-8579-c53928390afa.jpg)

**Comment by LloydRutledge** [comment]
Oskar: nice bug report, thanks.

Stef solved this short term on the RAP3 OU server by purging files to make disk room. Let's please keep addressing this as a long term issue. This type of disk overflow is the largest RAP problem each year for the Rule-based Design students. Keeps getting better each year, so thank you all very much. But this year it's still happening.

**Comment by LloydRutledge** [comment]
Are there prevention tips we can put in the documentation for students? Such as to delete stored files when they are no longer using them, or would that help?
