### ISSUE TITLE
RAP.cs.ou.nl cannot write local files

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#64]
The RAP3 server at rap.cs.ou.nl seems not to be able to write new files. I understand from Stef that he chatted with Michel about it and the concluded there may have been a problem with the install. Stef did a reinstall and the problem is still there.

You can enter a script and parse it and get parse error messages. But clicking compile generates "Error occurred while attempting to execute 'ampersand …. .adl'. Exitcode=1". Earlier I've been able to compile and generate links to generate files, but the files themselves don't appear on the server. When you click on one of the three generated links, you get "Not Found. The requested URL /RAP3/..." was not found on this server.

@stefjoosten can you look into this, and see if another re-install works? Or is this maybe a more stubborn bug. The students are now using a backup server, but this half-broken server is the official OU server for the course.

**Comment by stefjoosten** [comment]
This has been resolved by issue #68.
