### ISSUE TITLE
RAP3 is unfortunately named

### ISSUE THREAD

**Issue by maxeonyx** [AmpersandTarski/RAP#65]
Hello,

I found the Ampersand project today (looks like a great project!) and noticed that this project has an unfortunate name (in English). The 3 is similar to an E so it looks like "rape".

I understand that it was RAP -> RAP2 -> RAP3, however I thought I would point it out, it seems most of the contributors here are native German speakers, so might not have noticed. It's not a huge thing, just is a bit distracting and could be offensive to some readers.

**Comment by hanjoosten** [comment]
Haha, Thanks for pointing this out. I agree that it is unfortunate. The resemblance is purely coincidental. I don't think we will take specific action on this, other than that it could be an extra motivation to move on to a next version.
