### ISSUE TITLE
Configuration of RAP3 for easier deployment

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#66]
This issue is an enabler rather than a feature.
#### Problem
The configuration of RAP3, as described in the [Docker file](https://github.com/AmpersandTarski/RAP/blob/master/Dockerfile) and the [Docker-compose file](https://github.com/AmpersandTarski/RAP/blob/master/docker-compose.yml) yields large images with unnecessary dependencies. These dependencies pose undesirable obstacles for deploying RAP3. Our goal is to move to continuous deployment. This requires a configuration with small images and independent containers. A complication is that my active knowledge of cloud architecture (read: docker) is immature.

#### Diagnosis
I would expect separate containers for:
* MariaDB
done. The current container puts the data from the database in a volume, so it survives the container.
* phpMyAdmin
done. This is used by maintainers to inspect the database. By putting it in a container it can be brought down when no maintenance is done, which increases the security.
* Ampersand compiler
This should be a daemon. Currently, the Ampersand compiler contains a switch, `--daemon` that does this. This option is meant to keep an Ampersand compilation service alive in a container.
* Latex
Currently, we have texlive incorporated in the Ampersand compiler, which makes the image way too large. I would like to use a standard [texlive image from dockerhub](https://hub.docker.com/r/adnrv/texlive/) without alterations. Since the latex container is not always used, we might want to spin it up on demand and let it perish when done.
* Graphviz
The same goes for Graphviz. It should be in a separate container. Simple, for example like https://hub.docker.com/r/bennettp123/graphviz/dockerfile.
* VS-code
We also want to run Visual Studio Code in a separate container. It should replace the ACE editor in the current RAP-application, enabling us to use Git as an ampersand repository directly from VS-code. There are many images on dockerhub, e.g. https://hub.docker.com/r/joengenduvel/docker-vscode/dockerfile. I'm not sure which are useful. I guess we have some sorting out to do to have VS-code replace ACE.

#### Actions

TBD

**Comment by hanjoosten** [comment]
For the vscode part: There is work in progress. Have a look at [this blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development)

**Comment by stefjoosten** [comment]
This issue is stale. So I'm closing it

**Comment by stefjoosten** [comment]
This issue is resolved by the ongoing work on Kubernetes.
