### ISSUE TITLE
Files for prototype do not get created and thus later not found

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#68]
The rap.cs.ou.nl server says it generates prototypes successful but clicking on the link it provides gives this error

Warning: require_once(/var/www/html/RAP3/scripts/lloydr/generated/Script_1560956202_00515999/prototype/src/../lib/autoload.php): failed to open stream: No such file or directory in /var/www/html/RAP3/scripts/lloydr/generated/Script_1560956202_00515999/prototype/src/bootstrap.php on line 26

Fatal error: require_once(): Failed opening required '/var/www/html/RAP3/scripts/lloydr/generated/Script_1560956202_00515999/prototype/src/../lib/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/RAP3/scripts/lloydr/generated/Script_1560956202_00515999/prototype/src/bootstrap.php on line 26

Those files do indeed not appear in the file system's directory structure if you check using a command line interface. There is room on the disk. Recent (late) students have reported this error, and I have been able to recreate it.

Stef, can you look into this?

**Comment by stefjoosten** [comment]
I have reset RAP3 entirely and created sufficient room on the server. However, I did not get a proper explanation for what goes wrong. Here is the screenshot, taken after compiling a correct script and trying to generate a prototype:

<img width="1232" alt="Screen Shot 2019-11-22 at 15 56 57" src="https://user-images.githubusercontent.com/275768/69436004-db81b400-0d40-11ea-9fee-9cc7536fc8e3.png">

**Comment by hanjoosten** [comment]
As part of the prototype being generated, a specific version of the prototype framework is downloaded from the repository called `prototype`. The error message shows that the GET request to download it failed. It says that `github.com` cannot be found. 
It is very unlikely that github.com is down. I assume that the network where the container lives in, cannot reach the internet.

**Comment by stefjoosten** [comment]
I have contacted the OUNL people. They assured me that this server has full access to the internet.

**Comment by Michiel-s** [comment]
I agree with @hanjoosten, this doesn’t look like an issue in the Ampersand nor prototype framework code.

As the error shows, the compiler is trying to download stuff from github. This is a required step to initialize a prototype. But a connection failure error is thrown.

A google search gave me a couple of hints. One of them is about http and https proxy settings, but it can be something else.

I cannot help with this issue any further. Try bashing into the container and check if you can reach github (e.g. with curl). From there debug further for the library and function that is used by the Ampersand compiler.

**Comment by stefjoosten** [comment]
You have helped a lot, @Michiel-s ! Thanks to you I could make a diagnosis. The problem is indeed that the server `lnx-hrl-202v` (aka `rap.cs.ou.nl`) does not connect to the internet. I did the following experiment:
1. bash into the container and run `curl www.nu.nl`. It hung, so I had to `^C` out of it.
2. exit the container and run `curl www.nu.nl` from the server `lnx-hrl-202v`. It hung too, so I had to `^C` out of it.
3. exit from my ssh-session to the server and run `curl www.nu.nl` from my own laptop. It responds as it should.

Here is the proof
```
Last login: Fri Nov 22 15:37:57 2019 from 145.20.142.205
sjo@lnx-hrl-202v:~$ docker exec -it f8922d728c19 /bin/bash
root@f8922d728c19:/var/www/html# curl www.nu.nl
^C
root@f8922d728c19:/var/www/html# ping www.nu.nl
bash: ping: command not found
root@f8922d728c19:/var/www/html# exit
sjo@lnx-hrl-202v:~$ curl www.nu.nl
^C
sjo@lnx-hrl-202v:~$ logout
Connection to rap.cs.ou.nl closed.
BA92-C02VP224HTDF:RAP stefjoosten$ curl www.nu.nl
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
BA92-C02VP224HTDF:RAP stefjoosten$ 
```
So I'll get back to the OUNL-people to tell them that server `lnx-hrl-202v` does NOT have full access to the internet.

**Comment by stefjoosten** [comment]
This has helped. Issue closed
