### ISSUE TITLE
global unique naming voor CONTEXT problematic

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#70]
I get this issue with the OU server. When I copy the tutorial's Enrollment example code into a new script and try to compile it I get the error message

"Each ScriptContent may only have open Script in the relation content."

It seems this is because another user of the server already copied that code into a script, which defines "CONTEXT Enrollment" and then when another script with the same CONTEXT compiles this error occurs.

You can recreate it by starting a new script with this code:

CONTEXT Dupname
ENDCONTEXT

And compiling and saving it. And then making another new script with the same code, which delivers this error message, as shown in this screendump:

![image](https://user-images.githubusercontent.com/1098321/70631446-788f8880-1c2d-11ea-85b7-74d5025ecac5.png)

If you change the name of the CONTEXT then it does compile.

There are theoretical motivations for globally unique contexts. But beginning students want to simple be able to copy a starter's tutorial code into the system and have it work. Can we loosen this unique naming requirement, or make it optional on install?

**Comment by LloydRutledge** [comment]
This is the cause behind https://github.com/AmpersandTarski/RAP/issues/31

**Comment by stefjoosten** [comment]
### Diagnosis
This is a mistake in the RAP code. I have found the error on line 10 of the file `Scripts.adl`:
```
  RELATION content[Script*ScriptContent] [UNI,INJ]
   MEANING "The actual text of the script (as seen in the editor)."
```
Ampersand has no theoretical motivations for globally unique contexts. This is simply wrong.

**Comment by stefjoosten** [comment]
The code for RAP has been changed. So it will be fixed in the next release. (After the student-run of 2019 has finished)
