### ISSUE TITLE
Foutmelding uit "SIAMv4" ?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#71]
#### Situatie
Ik heb ingelogd met een bekende username-password combinatie. Uit het groen oplichten van de login-box maakte ik op dat het inloggen goed is verlopen. Ook verschenen de juiste functies in de navigatiebalk, wat ik vaststelde door de verschillende rollen te activeren en deactiveren.

#### Wat er gebeurde en wat ik verwachtte
Ik verwachtte dat ik nu aan de slag kon. Echter, boven de login-box verscheen ook een rode foutmelding: "You do not have access to this page". In de screenshot heb ik de foutmelding geopend, zodat de trace ervan zichtbaar is. Ik verwachtte dat deze foutmelding traceerbaar zou zijn naar de Ampersand-broncode, maar dat was niet het geval. Deze melding komt uit de code van Prototype.
<img width="1192" alt="Schermafdruk 2019-12-16" src="https://user-images.githubusercontent.com/275768/70883228-93b61b80-1fd2-11ea-8916-2d71d710dfd0.png">

#### Analyse
De applicatie meldt dat hij de interface `Login` niet kan vinden. Uit het screenshot hieronder blijkt dat de applicatie die wel degelijk kent.
<img width="644" alt="rollentabel 2019-12-16" src="https://user-images.githubusercontent.com/275768/70883595-c6144880-1fd3-11ea-8fbd-aab075e073a4.png">

Mijn hypothese:
Er is zojuist ingelogd, dus is de sessie-rol niet langer `Anonymous`. De rollentabel staat maar één rol toe voor de Login-interface, namelijk `Anonymous`. En dus signaleert "iets" deze inconsistentie. Dat iets is niet niet de exec-engine, want dat zou een Ampersand-foutmelding opleveren.

Ik ga ervan uit dat SIAMv4 dit soort dingen regelt, dus ben ik ook benieuwd wat @RieksJ  hiervan vindt.

**Comment by RieksJ** [comment]
Als je vanuit een anonieme sessie succesvol inlogt, dan worden de relaties `sessionAccount` en `sessionIsUser` gepopuleerd, en `sessionIsAnon` gedepopuleerd. Dat zijn triggers op basis waarvan rollen gezet worden en dergelijke. 

Maar er gebeurt nog iets anders: als de relaties `sessionUserIfc[SESSION*NavToIfc]` is gepopuleerd, dan springen we naar de hierin gespecificeerde (NavTo)interface. In het bestand `SIAMv4_Module-example` staat vanaf r 86 een voorbeeld dat je kunt gebruiken in je eigen SIAMv4 loader file en zo nodig aanpassen (bijvoorbeeld als je na een succesvolle login niet naar `/UserHome` wilt springen: 
~~~
--[Set default interfaces for anonymous sessions and user sessions]
{-    ROLE ExecEngine MAINTAINS "Set NavTo interfaces for session"
   RULE "Set NavTo interfaces for session": I[SESSION] |- sessionIfcsSet
   VIOLATION (TXT "{EX} InsPair;sessionUserIfc;SESSION;", SRC I, TXT ";NavToIfc;/UserHome" --<-- Deze interface verschijnt als je net bent ingelogd
--           ,TXT "{EX} InsPair;sessionAnonIfc;SESSION;", SRC I, TXT ";NavToIfc;/Login" -- de `Login` interface(s) kun je importeren vanuit SIAMv4
             ,TXT "{EX} InsPair;sessionAnonIfc;SESSION;", SRC I, TXT ";NavToIfc;/AnonHome" -- Hier kun je inloggen.
             ) --}
~~~
Vanuit de analyse denk ik dat `sessionUserIfc` niet is gezet. Bijgevolg wordt na een succesvolle login dan ook niet zomaar ergens heen gesprongen, maar blijft hij in de bestaande interface, te weten `Login`. Die interface is echter alleen toegankelijk voor de rol `Anonymous`, en die rol is zojuist gedeactiveerd - je bent immers succesvol ingelogd.

Suggestie: Neem de hierboven genoemde ExecEngine RULE op in je SIAMv4 loader file, en zorg dat de interfaces waar je heen wilt springen na een succesvolle login c.q. logout bestaan en voor de rol User respectievelijk de rol Anonymous toegankelijk zijn.

**Comment by stefjoosten** [comment]
Ja dat helpt. Het lost het nog niet helemaal op, maar ik zit nu op het juiste pad. Dank!

**Comment by hanjoosten** [comment]
Wel interessant. Het blijft een rode foutmelding. Zou dit statisch te detecteren zijn?

**Comment by stefjoosten** [comment]
I have closed this issue, because in newer versions it does not occur, so I have no pain anymore. Nevertheless, I am still curious to @RieksJ 's answer to my question. Because it might be that there is a bug in SIAM.

**Comment by RieksJ** [comment]
The code is correct, since `SetNavToOnCommit` is defined 
- to set the INTERFACE where navigation has to continue, possibly overriding an earlier setting thereof in the same transaction
- to act as a no-operation in case it receives a `_NULL` argument. 

So if the code you show is the last occurrance of `SetNavToOnCommit` in the transaction, then navigation should continue at the INTERFACE `MyAccount`, since the subsequent `_NULL` argument is ignored, as is shown in the log line:
`[2019-12-18 11:03:20] EXECENGINE.DEBUG: navTo was skipped because of '_NULL'-argument`

**Comment by stefjoosten** [comment]
Thx!
