### ISSUE TITLE
Prototype generation in RAP does not work with Ampersand 4.0.0

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#73]
With the script `Enrollment.adl` I wanted to generate a prototype. However, it failed.

#### Version of Ampersand
I am using RAP that has been compiled with AmpersandTarski/Ampersand@20be24784dec0a42b2ffe39a872e920dc9d3a195 of Jan 8th, 2020. I am using RAP at commit 230005e9c217a5335697dc5aed667daab97db0ff in branch `reconfiguring-RAP`.

#### What I expected
I was hoping this would work

#### What happened
<img width="1680" alt="Schermafdruk 2020-01-08 15 17 24" src="https://user-images.githubusercontent.com/275768/71986231-66a10580-322c-11ea-8f46-14988c6ed4d7.png">
It says `composer: not found`.

I have tried to install composer from the rap3 container, for the purpose of finding out what to type in the RAP3 Dockerfile. I couldn't figure it out, however.

#### How to reproduce
1. deploy RAP
2. log in as a user
3. navigate to "Create new script"
4. Paste Enrollment.adl in the editor and compile
5. press the `Prototype` button

**Comment by hanjoosten** [comment]
Installing composer requires an internet connection, to go to getcomposer.org. Composer isn't (properly) installed, because composer cannot be found. 
Is composer part of one of the docker files?
