### ISSUE TITLE
Prototype generation in RAP does not work with Ampersand 4.0.0

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#74]
Still working on RAP. Atlas works now. But the prototype button still doesn't work (and the diagnosis button and functional spec button give similar behaviour).

#### Version of RAP
I'm working with RAP repository's commit bd3733c47f0b621a47a79ae7bd84acbcce3c47a2.
It has been compiled with Ampersand-v4.0.0 [development:7b592a324*] docker image 5861e8d9533e.

#### Situation
After pressing the `Prototype`-button the prototype has been generated. Peeking in the container shows that:
```
root@5861e8d9533e:/var/www/data/scripts/pietertje/Script_1579880461_00692578# ls -al
total 0
drwxr-xr-x  5 root root 160 Jan 24 15:43 .
drwxr-xr-x  3 root root  96 Jan 24 15:41 ..
drwxr-xr-x  3 root root  96 Jan 24 15:41 ScriptVersion_1579880513_00617706
drwxr-xr-x  4 root root 128 Jan 24 15:42 ScriptVersion_1579880551_00106193
drwxr-xr-x 30 root root 960 Jan 24 15:43 proto
root@5861e8d9533e:/var/www/data/scripts/pietertje/Script_1579880461_00692578# ls proto -al
total 376
drwxr-xr-x 30 root root    960 Jan 24 15:43 .
drwxr-xr-x  5 root root    160 Jan 24 15:43 ..
-rw-r--r--  1 root root     55 Jul 22  2019 .bowerrc
-rw-r--r--  1 root root     42 Jan 24 15:43 .frameworkSHA
-rw-r--r--  1 root root     77 Jul 22  2019 .gitignore
-rw-r--r--  1 root root    182 Jul 22  2019 .htaccess-production
-rw-r--r--  1 root root    172 Jul 22  2019 .jshintrc
drwxr-xr-x  3 root root     96 Jan 24 15:43 .phan
drwxr-xr-x  3 root root     96 Jan 24 15:43 .vscode
drwxr-xr-x  3 root root     96 Jan 24 15:43 app
-rw-r--r--  1 root root    196 Jul 22  2019 babel.config.js
drwxr-xr-x  4 root root    128 Jan 24 15:43 bootstrap
-rw-r--r--  1 root root    828 Jul 22  2019 bower.json
-rw-r--r--  1 root root   4336 Jul 22  2019 changelog.md
-rw-r--r--  1 root root   1016 Jul 22  2019 composer.json
-rw-r--r--  1 root root  67179 Jul 22  2019 composer.lock
drwxr-xr-x  4 root root    128 Jan 24 15:43 config
drwxr-xr-x  3 root root     96 Jan 24 15:43 data
drwxr-xr-x  3 root root     96 Jan 24 15:43 extensions
drwxr-xr-x 13 root root    416 Jan 24 15:44 generics
-rw-r--r--  1 root root   4671 Jul 22  2019 gulpfile.js
drwxr-xr-x 15 root root    480 Jan 24 15:44 lib
drwxr-xr-x  3 root root     96 Jan 24 15:43 log
-rw-r--r--  1 root root 254673 Jul 22  2019 package-lock.json
-rw-r--r--  1 root root   1213 Jul 22  2019 package.json
-rw-r--r--  1 root root      0 Jul 22  2019 phan-issues.txt
-rw-r--r--  1 root root    204 Jul 22  2019 phpcs.xml
drwxr-xr-x  5 root root    160 Jan 24 15:43 public
drwxr-xr-x  3 root root     96 Jan 24 15:43 src
drwxr-xr-x 37 root root   1184 Jan 24 15:43 templates
root@5861e8d9533e:/var/www/data/scripts/pietertje/Script_1579880461_00692578# 
```

**Comment by hanjoosten** [comment]
Het euvel lijkt hier dat je start in `/var/www/data/scripts/pietertje/Script_1579880461_00692578/proto`.
 we maken tegenwoordig prototypes die moeten starten van uit de `public` directory in de gegenereerde prototype. In dit geval dus `/var/www/data/scripts/pietertje/Script_1579880461_00692578/proto/pyblic`.  

See also https://github.com/AmpersandTarski/Ampersand/issues/892

**Comment by Michiel-s** [comment]
De var/www/data map is afgeschermd en niet rechtstreeks toegankelijk voor gebruikers. Dit gaat niet werken.
Zie hiervoor de berichten in de whatapp die we hadden. Misschien goed die hier even te plaatsten.

**Comment by hanjoosten** [comment]
[16:06, 1/8/2020] Michiel Stornebrink: Sorry, lukt komende dagen niet helaas. Zit rammend vol met afspraken.
Ik denk overigens dat de huidige werkwijze niet gaat werken voor prototypes, omdat de betreffende studenten proto folders niet open staan naar buiten. Alleen de /public voor de RAP3 applicatie zelf.
[16:06, 1/8/2020] Michiel Stornebrink: Zoals ik eerder aangaf denk ik dat de beste route is om een dockerimage samen te stellen voor het bouwen en runnen van studenten prototypes.
[16:07, 1/8/2020] Michiel Stornebrink: Vervolgens vanuit RAP per student script een container starten met dit image.
[16:09, 1/8/2020] Michiel Stornebrink: Uitdaging is het opzetten van de proxy, zodat bijvoorbeeld https://student.rap3.ou.nl/<studentnr> uitkomt bij de betreffende container.
[16:12, 1/8/2020] Michiel Stornebrink: Oh, nu ik erover nadenk moet het denk ik nog net iet anders en makkelijker.
[18:28, 1/8/2020] Michiel Stornebrink: Voorstel:
- we maken 1 image specifiek voor het runnen van RAP studenten scripts. Deze image pakt het prototype framework als basis, maar met enkele specifieke wijzigingen (zie verderop)
- van deze image maken we 1 container die de studenten prototypes serveert.
- container maken we beschikbaar via student.rap3.ou.nl
- studenten prototypes zijn dan beschikbaar onder student.rap3.ou.nl/<student nummer>
- de map waar de gegenereerde frontend js+html en backend json files staan mounten we in zowel de RAP3 container als ook bovengenoemde container. Zo kunnen we vanuit rap3 prototypes genereren.
- het prototype framework hoeft niet per student script geïnstalleerd worden, want de basis is voor alles hetzelfde, dit zit al in de container. Dat scheelt veel generatie tijd, schijfruimte. Maar vergt wel wat aanpassingen
[18:40, 1/8/2020] Michiel Stornebrink: Ik denk overigens dat dit bij elkaar 2 volle dagen werk is. Aanpassingen die nodig zijn:
- backend api moet <student nummer> oppakken en juiste ‘generics’ map pakken voor backend configuratie
- frontend applicatie moet configuratie krijgen voor api path (zodat student nummer toegevoegd wordt)
- de juiste frontend files gebundeld in project.js en project.css moeten worden ingeladen in index.html. Hier kunnen we voor deze rap3 toepassing een specifieke aanpassing doen.

**Comment by stefjoosten** [comment]
# Uitwerking
Zodra je op de "Prototype-knop" drukt (in het RAP3-editscherm) draait docker een rap3-student-proto container (met daarin het scriptje "run-student-proto.sh"). Dat commando ziet er in PHP als volgt uit:
```
        "echo \"{$scriptContentForCommandline}\" | docker run",
        [ "-v /var/run/docker.sock:/var/run/docker.sock", // for communicating with the docker repo outside this container
          "--name \"{$userName}\"",
     //   "--rm",
          "-i",
          "-a stdin stderr",  // stderr ensures that fatals reach the end user. Without stderr, the end user gets to see the container id.
          "-p 8081:80", // TODO: remove this argument, because we don't want to expose directly on host, but use reverse-proxy instead
          "--network rap_db",
          "-e AMPERSAND_DBHOST=db",
          "-e AMPERSAND_DBNAME=\"{$userName}\"",
          "rap3-student-proto" // image name to run
        ],

**Comment by hanjoosten** [comment]
We krijgen nu nog een foutmelding:
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=stefj: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```
Ik weet nog niet precies wat hier aan de hand is, maar [dit](https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket) is een link die hier relevant is.

**Comment by Michiel-s** [comment]
@hanjoosten, ik heb het niet uitgeprobeerd, maar ik denk dat het te maken heeft dat jij Docker for Windows draait en @stefjoosten op een mac zit. De docker deamon is voor beide systemen niet op dezelfde locatie beschikbaar.
Dus de volume bind die in de RAP3 genereer student prototype staat `-v /var/run/docker.sock:/var/run/docker.sock` werkt denk ik niet op Windows.

Zie: https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows

**Comment by hanjoosten** [comment]
@Michiel-s , dank voor de update. Ik ben nog niet overtuigd. Na mijn laatste commentaar hierboven hebben Stef en ik nog een keer gezeten. Het is toen (op mijn machine) gelukt om vanaf de prototype knop een container te starten: Er kwam een container-id in beeld. 100% zeker dat dit is gebeurd.
Echter ik krijg dit nu even niet meer zo aan de praat. Lijkt me wel weer leuk om binnenkort samen weer aan de slag te gaan. Dat soort sessies zijn uitermate nuttig. Heb je binnenkort nog tijd?

**Comment by Michiel-s** [comment]
I think you can close this issue as Stef is moving towards deployment with kubernetes. I any case it is not wise to give access to the docker daemon on a host machine from a security perspective. Fine for dev, not ok for production.
