### ISSUE TITLE
Prototype doesn't work

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#81]
#### Versie van Ampersand (in de CLI:  >  ampersand --version)
I heb een app gemaakt, [Klantkaart](https://github.com/AmpersandTarski/RAP/tree/deploy-2020/Demos/Klantkaart/Klantkaart.adl) en gecompileerd in RAP, die was gegenereerd vanuit AmpersandTarski/RAP@b03b4861534d80ff637f3f39f8f0d71a4b51814a (the RAP-repo). I draai RAP lokaal op mijn MacBook Pro.

#### Wat ik verwachtte
Ik verwachtte een werkend prototype te zien na het klikken op "Open Prototype" in de RAP "create script" interface.

#### Wat er gebeurde
Ik kreeg dit te zien:
<img width="400" alt="Schermafbeelding 2020-10-21 om 15 58 57" src="https://user-images.githubusercontent.com/275768/96731311-66d35180-13b7-11eb-88ae-961a077e7b60.png">

#### Analyse
Ik ben in de container `stefj` gekropen en stel vast dat de environment variabelen voor een prototype niet gezet zijn.  De variabelen die wél in de container `enroll` zitten maar niet in `stefj` zijn:
```
      - AMPERSAND_LOG_CONFIG=logging.yaml
      - AMPERSAND_DEBUG_MODE=false
      - AMPERSAND_PRODUCTION_MODE=false
      - AMPERSAND_DBHOST=db # refers to database service below
      - AMPERSAND_DBUSER=${MYSQL_USER}
      - AMPERSAND_DBPASS=${MYSQL_PASSWORD}
      - AMPERSAND_DBNAME=enroll
      - AMPERSAND_SERVER_URL=https://${SERVER_HOST_NAME}
```
Het is dus niet verwonderlijk dat het niet werkt...

####Analyse 2
Ik ben teruggegaan naar de versie van gisteren, en daar werkte het wel. Dus ik moet iets verprutst hebben....

**Comment by Michiel-s** [comment]
Volgens mij was het probleem hier dat er www. voor stond. Zie screenshot. Dat domein werkte niet. Moest zonder www zijn.
