### ISSUE TITLE
Student container doesn't work; environment variables in rap4-student-prototype are not set

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#85]
#### De situatie
Ik heb een prototype gemaakt, `Klantkaart.adl`, vanuit mijn studenten-account `stefj`, om te testen of ik prototypes kan draaien op RAP4.

#### Wat er gebeurde er en wat had je verwacht?
Ik heb dit prototype gestart door op de blauwe "Prototype"-knop te drukken, en zie op de server keurig netjes een container verschijnen:
```
  CONTAINER ID   IMAGE                                           COMMAND                  CREATED          STATUS         PORTS   NAMES
  3b13acbe076f   ampersandtarski/rap4-student-prototype:v1.0.0   "/bin/sh -c 'bash /r…"   12 seconds ago   Up 10 seconds  80/tcp  stefj
```
Deze container is toegankelijk vanuit mijn browser:
<img width="400" alt="Schermafbeelding 2020-10-24 om 08 14 31" src="https://user-images.githubusercontent.com/275768/97069480-04ee3400-15d1-11eb-8652-9d1b3dcd738f.png">
Opvallend is dat de beveiliging niet werkt, dus heb ik gekeken naar de environment variabelen. Ik had verwacht de volgende Ampersand-specifieke omgevingsvariabelen aan te treffen:
```
RAP_HOST_NAME=rap.cs.ou.nl
AMPERSAND_PRODUCTION_MODE=true
AMPERSAND_DBNAME=stefj
AMPERSAND_DBUSER=ampersand
AMPERSAND_DBPASS=ampersand # (password tweaked for security reasons)
AMPERSAND_DEBUG_MODE=false
AMPERSAND_SERVER_URL=https://rap.cs.ou.nl
AMPERSAND_LOG_CONFIG=logging.yaml
AMPERSAND_DBHOST=db
RAP_STUDENT_PROTO_IMAGE=ampersandtarski/rap4-student-prototype:v1.0.0
```
Echter, wat ik hiervan in de container `stefj` aantrof was:
```
AMPERSAND_DBNAME=stefj
AMPERSAND_DBHOST=db
```

#### Stappen om dit te reproduceren
1. 
2.
3.
4.

**Comment by Michiel-s** [comment]
Should be fixed now. I've tested it locally.

**Comment by stefjoosten** [comment]
Check! It works
