### ISSUE TITLE
Violation of rule 'identity_Interface'

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#93]
I'd saved the Enrollment example on the RBD course RAP4 server. Previously it generated the Bad Gateway error. Now when I compile it, it gives two Violation of rule 'identity_Interface' errors, as shown here:

![Naamloos](https://user-images.githubusercontent.com/1098321/100497273-91ed5580-315a-11eb-9255-d6a5ba0e7ac7.png)

The phrase 'identity_Interface' appears nowhere in the script. Any ideas?

**Comment by LloydRutledge** [comment]
The problem occurs when I generate the Atlas after a fresh compile.

**Comment by hanjoosten** [comment]
I am not sure, but my guess is that this could very well be an unfortunate case of one of our unsolved issues: Namespaces. 

I am not going to explain all that here, but if I am right, there is a conflict in the naming of interfaces. An interface in this script has the exact same name as an interface in formalAmpersand, which is used to generate the atlas. 
As a workaround, you could rename the interface named "Overview" to some other name. If my guess is correct, this will get the script running. It is not a real fix, but it might do for now. 

@LloydRutledge Please let us know what happens!

**Comment by stefjoosten** [comment]
Can Lloyd rename an interface?

**Comment by hanjoosten** [comment]
Sure! It is in his own script.

**Comment by LloydRutledge** [comment]
I renamed the INTERFACE Overview to Overview2 and still have the same problem when generating the atlas. Also renamed to Overview98987 and still the same problem.

**Comment by stefjoosten** [comment]
This issue is the same as #102 and #96. It has been fixed.
