### ISSUE TITLE
Reused names shared between saved scripts of different students on the RAP4 server?

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#96]
*NOTE: this is the same issue as #102 (this note was added in retrospect by SJ)*

Is it possible that reused names are shared between saved scripts of different students on the RAP4 server? Is this possibly related to the Namespace problem that @Michiel-s has mentioned?

Is suspect this because the OU Rule-based Design students had as their Ampersand assignment last week that they load the example script at https://ampersandtarski.gitbook.io/documentation/tutorial-rap3 and follow the instructions there for adding data via the prototype interface. Students have been posting reports of unexpected behavior that is consistent with a shared namespace across all scripts of all students. That is that students report that when they first load the script and run the prototype to follow instructions for adding data, they see that the data they are still supposed to add is already there. And one reported following an instruction to remove data in order to get a violation message which didn't come. Perhaps that's because the data was removed from her script but still in someone else's?

Is a short-term fix to tell the students to make new names for their CONTEXTs? Then I'll tell them that when issue 92 is resolved and the prototype functionality runs on the server again.

We have 70 students who had this reading assignment last week, and they all have a specific new assignment each coming week until February. These assignments and the use of Ampersand are optional in the course so it is not a disaster if they use alternatives but it may be a missed opportunity. I appreciate all the hard work done here and understand that cutting edge development like this necessarily focuses more on broad functionalities than deep robustness because of limited programming resources and the relatively high cost of robustness testing. Hopefully, we can get the robustness high enough for this broader group so they can fully appreciate the tool.

**Comment by stefjoosten** [comment]
It is unlikely that reused names are shared across prototypes of students. Each student gets a database whose name contains the student's login name. So student `ohare` gets a database with name `student_ohare`. But this thought does provoke a line of analysis....

**Comment by hanjoosten** [comment]
@Stefjoosten, We missed something: If a student has multiple (versions) of scripts, we need to remove all contexts. The context that we need to remove isn't nesceserilly attached to the current scriptversion. We need to remove every previously generated atlas by that user. In the file RAP4.adl around line 100, this seems to be in place. Obviously this is a far more elegant way of triggering the action to cleanup a specific atlas. 

~~~
--[Deletion of Context (Fully cascading!)]--
RELATION requestDestroy[Context*Context] [PROP] -- a request to destroy this context. Beware: Experimental. You might burn all. The idea is that ALL atoms in the context of RAP4 that are linked with this context atom (transitive closure) will be deleted. ALL relations are taken into account, except for a set, specified in cli.php. Currently, the only relation in that set is context[ScriptVersion*Context]. This is to avoid that atoms are destroyed in the specific RAP4 part. 
ROLE ExecEngine MAINTAINS "Destroy Context"  -- ExecEngine is een echte pyrotechnicus.... 
RULE "Destroy Context" : requestDestroy |- -V
VIOLATION ( TXT "{EX}Cleanup;", SRC I, TXT ";Context"
~~~

I guess that if we revive this piece of code, and include a rule that any user can only have a single atlas populated for all of her script(version)s, this should work.

**Comment by stefjoosten** [comment]
fixed. See issue #102
